openweave/openweave-core

src/inet/InetLayer.cpp
src/system/SystemObject.h
src/system/SystemStats.cpp
src/system/SystemStats.h
src/system/SystemTimer.h
src/test-apps/TestSystemObject.cpp

SystemObject pools lacked the implementation of the high water mark.

Added high water mark support for SystemObject pools

---

src/device-manager/WeaveDeviceManager.cpp
src/device-manager/WeaveDeviceManager.h
src/device-manager/python/weave-device-mgr.py
src/lib/core/WeaveConfig.h
src/lib/core/WeaveError.h
src/lib/profiles/network-provisioning/NetworkProvisioning.cpp
src/lib/profiles/network-provisioning/NetworkProvisioning.h
src/lib/support/ErrorStr.cpp
src/lib/support/WeaveNames.cpp
src/test-apps/MockNPServer.cpp

To achieve that, the following has been implemented:
* Added new version of AddNetwork() message - kMsgType_AddNetworkV2.
* Implemented mechanism, which automatically resends old version of
AddNetwork() message if the new version of that message is not
supported by the device.
* Added new Create Thread Network (create-thread-network) command
to the Python Device Manager.

Add support for standalone Thread network creation command.

---

src/lib/profiles/data-management/Current/SubscriptionClient.cpp

The spec says the PathList is optional but cannot be empty.
CheckSchemaValidity is right, but the actual encoder and parser do the
opposite.
Reverting the call to CheckSchemaValidity for now; it had been
added mainly for logging purposes.
We'll realign the implementation to the spec later.

Reverted a call to SubscribeRequest::CheckSchemaValidity

---

src/inet/AsyncDNSResolverSockets.cpp
src/inet/AsyncDNSResolverSockets.h
src/inet/DNSResolver.cpp
src/inet/DNSResolver.h
src/inet/InetError.h
src/inet/InetLayer.cpp
src/inet/InetLayer.h
src/lib/support/ErrorStr.cpp
src/test-apps/TestDNSResolution.cpp
src/test-apps/ToolCommon.cpp

(This work is part of WEAV-3088).
-- Enhanced the System Layer’s ResolveHostAddress() API to provide an option for controlling the type and ordering of IP addresses to be returned by DNS name resolution.  Available options are: IPv4Only, IPv6Only, IPv4Preferred, IPv6Preferred.
-- Revised the handing of some corner-case DNS errors on sockets platforms.  The net effect is that, in some cases where DNS records of the appropriate type do not exist, ResolveHostAddress() will return INET_ERROR_HOST_NOT_FOUND rather than an empty list of addresses.  This is consistent with how higher layer code treated these cases (specifically WeaveConnection and WeaveBinding).
-- Consolidated the implementation of ResolveHostAddress() on sockets platforms between the synchronous and asynchronous …

Enhancements to DNS name resolution

---

src/lib/profiles/service-directory/ServiceDirectory.cpp
src/lib/profiles/service-directory/ServiceDirectory.h

Implement a trivial constructor that initializes the member variables
as needed.  This permits compilation without strict C++11 language
semantics and resulting support for uniform C++11 initialization.

Implement ServiceConnectBeginArgs constructor

---

src/lib/core/WeaveBinding.cpp
src/lib/core/WeaveBinding.h
src/lib/core/WeaveConnection.cpp
src/lib/core/WeaveMessageLayer.h
src/lib/profiles/service-directory/ServiceDirectory.cpp
src/test-apps/TestBinding.cpp
src/test-apps/ToolCommonOptions.cpp
src/test-apps/ToolCommonOptions.h

-- Modified WeaveConnection, WeaveServiceManager and Weave Binding, along with a few
test apps, to not reference DNSOptions when Weave is built with DNS name resolution
support disabled.

Fix build issues when DNS resolver disabled

---

src/lib/profiles/data-management/Current/MessageDef.cpp

* Add a missing sentinel s.t. we can compile w/o WEAVE_DETAIL_LOGGING
* Adapt the error handling prints for the current StatusElement format

Fix detail logging related issues

---

src/adaptations/device-layer/ServiceProvisioningServer.cpp

Fixed compilation error in device layer when WEAVE_DEVICE_CONFIG_DISABLE_ACCOUNT_PAIRING is set.

Fix device layer compilation error

---

src/lib/core/WeaveExchangeMgr.cpp

Before this patch, the `WeaveExchangeManager::mWRMPTimeStampBase` was
not adjusted properly following a long period of inactivity.
`GetTickCounterFromTimeDelta` returns a uint32_t; when that number
exceeded UINT16_MAX, the cast truncated most significant bits.  As a
result, the resetting of the `mWRMPTimeStampBase` assigned a value
that was too low, which in turn, led the computation of
`timerArmValue` inside `WeaveExchangeManager::WRMPStartTimer` around
line 1171 to produce a large negative value instead of a small
positive value.  This change fixes the computation of the
mWRPMTimeStampBase to align with the most recent timestamp
corresponding to the expired WRMP tick.

Fix timeout computation for WRMP after long inactivity

---

src/Makefile.am
src/Makefile.in

The test script, TestWeaveTool.py, runs against the 'weave' tool produced by tools/weave/.... Consequently, tools/weave must be iterated and built before test-apps. Otherwise, the TestWeaveTool.py test will fail.
This reorders SUBDIRS such that tools/weave appears before test-apps to satisfy this dependency.

Address a Unit Test Failure against TestWeaveTool.py

---

src/lib/profiles/data-management/Current/SubscriptionClient.cpp

Looks like this state was added quite a while after the EndSubscription code was written, so maybe it was left out accidentally.

Handle ending sub while in resubscribe holdoff

---

src/system/SystemTimer.cpp

Previous commit to address the unbounded number of timers was
incomplete -- it neglected to account for assumptions made within
SystemTimer::Cancel(), and within allocating a new timer.  This commit
performs two things:
* It restores the timer code to the state prior to commit
99f546478fccf259827c9426823dcb9223ffffaa
* It bounds the number of timers executed within the
Timer::HandleExpiredTimers() by constraining the number of timers
processed to the size of the timer pool.
This approach offers the following advantages:
* Fallback to the old code with the minimal changes
* No data-structure-related changes as compared with the old code.
The policies for maintaining all queues are the same as those prior
to 99f546478fccf259827c9426823dcb9223ffffaa.
As compared with the "eager" bounding of …

Ensure that the timer handling code processes a bounded number of timers

---

src/platform/ble/bluez/Makefile.am
src/platform/ble/bluez/Makefile.in

There is currently an issue in top-of-tree when building against LwIP with BLE support in which that library cannot find lwip/opt.h.
This addresses the issue by including network CPPFLAGS (LwIP and sockets).

Ensure Network CPPFLAGS (LwIP in Particular) Are Included for the BLE Platform Library

---

src/test-apps/MockTimeSyncClient.cpp

Simply closing the connection was leaving a TCP socket retrying
transmissions in a failed case when running with plaid, and that in
turn was being flagged as a resource leak.
Change-Id: Ic25ec1fe16381e74e77c83dc66a35ccc4e519775

Added code to abort the mock time sync client connection on failure

---

src/adaptations/device-layer/ServiceProvisioningServer.cpp
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/ServiceProvisioningServer.h
src/lib/core/WeaveConfig.h
src/lib/profiles/service-provisioning/ServiceProvisioning.cpp
src/lib/profiles/service-provisioning/ServiceProvisioning.h
src/lib/profiles/service-provisioning/ServiceProvisioningServer.cpp
src/test-apps/MockSPServer.cpp
src/test-apps/MockSPServer.h

Legacy devices in the field would employ IFJ to join the Weave
fabric of the Structure so that they can communicate using Weave
with the rest of the Weave devices in the home.
This message would be used by that device, at the end of IFJ, to
signal successful completion of the process to the Service.
After this communication, the device is formally part of the
Weave fabric of the structure and can assist other new device
pairings as well.

ServiceFabricJoin message definition for In-field Joining(IFJ) in Service Provisioning profile.

---

src/lib/profiles/common/CommonProfile.h
src/lib/support/StatusReportStr.cpp

Added a new Common Profile status code for use when an operation is rejected because one or more necessary local configuration steps have not been completed. “Local configuration steps” in this context means any prerequisite actions that must be performed locally on the target, e.g. physically connecting wires to a device, before the requested operation can be invoked.

Add Common:LocalSetupRequied status code

---

src/lib/profiles/data-management/Current/LoggingManagement.cpp
src/lib/profiles/data-management/Current/LoggingManagement.h
src/test-apps/MockExternalEvents.cpp
src/test-apps/MockExternalEvents.h
src/test-apps/TestEventLogging.cpp

Inside an application's fetch event callback, it can call a new
API, LoggingManagement::SkipEvent, instead of
LoggingManagement::BlitEvent if for some reason it is not able
to provide the corresponding event data.
Change-Id: I1ecddb26e7c1aec377a49442a331702221ee9549

Enable applications to skip providing data for an external event.

---

src/inet/IPAddress.cpp
src/inet/IPAddress.h
src/test-apps/TestInetAddress.cpp
src/test-apps/ToolCommon.h

This is the first of a series of pull requests to add more complete multicast support to the Inet layer.

Add Support and Unit Tests for Both IPv4 and IPv6 Multicast Address Introspection and Detection

---

src/inet/RawEndPoint.cpp
src/test-apps/TestInetEndPoint.cpp

While the Inet layer raw IP end points are tested in a number of places functionally, return values from several method calls are dropped and go unchecked.
To address this, this change set first enforces the correct state on raw IP end point listen, to make its behavior consistent with UDP and TCP end points.
Second, this change set check returns values from raw IP endpoint bind and listen operations in _TestInetEndPoint_, handling them in a stateful way such that the test passes and fails when it should.

Improve TestInetEndPoint Assertions

---

build/cstyle/cstyle.options
src/include/Makefile.am
src/include/Makefile.in
src/inet/IPEndPointBasis.cpp
src/inet/IPEndPointBasis.h
src/inet/InetLayer.am
src/inet/Makefile.in
src/inet/UDPEndPoint.cpp
src/inet/UDPEndPoint.h
src/lib/Makefile.in

This is the first in a series of refactorings that migrates common BSD-socket-specific implementation out of the UDPEndPoint class and into a new, intermediate IPEndPoint basis class from which the UDPEndPoint class will now derive.
The intent of this is two fold:
1. The intermediate IPEndPoint basis class will serve as a future home for forthcoming new common, expanded IP multicast implementation, particularly for BSD sockets, but also for LwIP.
2. The intermediate IPEndPoint basis class will serve as a point to further unify and harmonize IP datagram operations between RawEndPoint and UDPEndPoint, including unifying IPPacketInfo, since these two classes are more similar than different.

First Round of Refactoring for UDPEndPoint

---

src/device-manager/python/weave-device-mgr.py

When the add-thread-network command is used in more recently defined pairing workflows, the thread network key may be unspecified. On enabling such a network provision, the Weave device is expected to generate its own new thread network key in that case.

DeviceManager.py: Allow add-thread-network with unspecified thread network key.

---

src/inet/IPEndPointBasis.cpp
src/inet/IPEndPointBasis.h
src/inet/RawEndPoint.cpp
src/inet/RawEndPoint.h
src/inet/UDPEndPoint.cpp
src/inet/UDPEndPoint.h
src/test-apps/TestInetEndPoint.cpp
src/test-apps/TestInetLayer.cpp

This is the second round of refactoring of common IP datagram endpoint implementation, this time mostly focusing on rebasing the raw IP endpoint implementation atop of the common implementation and harmonizing, where possible, the raw IP and UDP endpoint implementations.

Second Round of Refactoring for RawEndPoint 

---

src/test-apps/happy/tests/service/pairing/test_weave_pairing_01.py
src/test-apps/happy/tests/standalone/inet/test_weave_inet_01.py
src/test-apps/happy/tests/standalone/pairing/test_weave_pairing_01.py
src/test-apps/happy/tests/standalone/servicedir/test_service_directory_01.py
src/test-apps/happy/tests/standalone/tunnel/test_weave_tunnel_01.py
src/test-apps/happy/tests/standalone/tunnel/test_weave_tunnel_02.py
src/test-apps/happy/tests/standalone/tunnel/test_weave_tunnel_03.py
src/test-apps/happy/tests/standalone/tunnel/test_weave_tunnel_04.py
src/test-apps/happy/tests/standalone/tunnel/test_weave_tunnel_faults.py
src/test-apps/happy/tests/standalone/wrmp/test_weave_wrmp_01.py

To date, there are a number of functional tests that are intentionally and programmatically skipped when Weave is configured for LwIP. Make these omissions more clear by emitted red-highlighted warnings in test log output.

Warn in Test Output about Skipped Happy Tests Due to LwIP Conifiguration

---

src/inet/IPEndPointBasis.cpp
src/inet/IPEndPointBasis.h
src/inet/InetLayer.h
src/inet/RawEndPoint.cpp
src/inet/RawEndPoint.h
src/inet/TunEndPoint.h
src/inet/UDPEndPoint.cpp
src/inet/UDPEndPoint.h
src/lib/core/WeaveMessageLayer.cpp
src/ra-daemon/RADaemon.cpp
src/ra-daemon/RADaemon.h
src/test-apps/TestInetLayer.cpp

This is the third round of refactoring of common IP datagram endpoint implementation, this time mostly focusing on harmonizing the OnMessageReceived callback function API between the two end points, passing IPPacketInfo as the third parameter for both.

Third Round of Refactoring Raw and UDP End Points

---

third_party/lwip/repo/lwip/src/api/if.c
third_party/lwip/repo/lwip/src/api/netifapi.c
third_party/lwip/repo/lwip/src/api/sockets.c
third_party/lwip/repo/lwip/src/api/tcpip.c
third_party/lwip/repo/lwip/src/core/init.c
third_party/lwip/repo/lwip/src/core/ipv4/autoip.c
third_party/lwip/repo/lwip/src/core/ipv4/dhcp.c
third_party/lwip/repo/lwip/src/core/ipv4/ip4.c
third_party/lwip/repo/lwip/src/core/ipv6/ip6.c
third_party/lwip/repo/lwip/src/core/mem.c
third_party/lwip/repo/lwip/src/core/netif.c
third_party/lwip/repo/lwip/src/core/pbuf.c
third_party/lwip/repo/lwip/src/core/raw.c
third_party/lwip/repo/lwip/src/core/tcp.c
third_party/lwip/repo/lwip/src/core/tcp_in.c
third_party/lwip/repo/lwip/src/core/tcp_out.c
third_party/lwip/repo/lwip/src/core/timeouts.c
third_party/lwip/repo/lwip/src/core/udp.c
third_party/lwip/repo/lwip/src/include/lwip/if.h
third_party/lwip/repo/lwip/src/include/lwip/ip.h
third_party/lwip/repo/lwip/src/include/lwip/netif.h
third_party/lwip/repo/lwip/src/include/lwip/netifapi.h
third_party/lwip/repo/lwip/src/include/lwip/opt.h
third_party/lwip/repo/lwip/src/include/lwip/prot/tcp.h
third_party/lwip/repo/lwip/src/include/lwip/raw.h
third_party/lwip/repo/lwip/src/include/lwip/stats.h
third_party/lwip/repo/lwip/src/include/lwip/tcp.h
third_party/lwip/repo/lwip/src/include/lwip/udp.h
third_party/lwip/repo/lwip/src/include/posix/net/if.h
third_party/lwip/repo/lwip/src/netif/ppp/vj.c

Outside of link local multicast addresses and the stack-required all-nodes, all-routers, and solicited node multicast addresses, the state of generalized IPv6 multicast support in LwIP was a bit spotty.
This pull request cherry-picks and adapts the minimal set of upstream multicast-related patches necessary to get a set of multi-node site-local multicast functional tests working:
- 1b20e664b: Task #14314: Add interface name/index APIs
- ab8119360: udp: add core-level multicast support for IPv6
- b33b3bb8b: Start working on task #14780: Add debug helper asserts to ensure threading/locking requirements are met
- f334ac68b: Work on task #14780: Add debug helper asserts to ensure threading/locking requirements are met Add LWIP_ASSERT_CORE_LOCKED() in several places
- aea706222: raw: extend …

Add Set of Upstream Patches to Get Generalized IPv6 Multicast Working in LwIP

---

third_party/lwip/repo/lwip/src/core/dns.c

-- Corrected logic bug in LWIP_ASSERT statement in dns_exec_found_callback().

Fix for Issue 122: TestDNSResolution: Assert in dns_exec_found_callback: "invalid table index"

---

third_party/lwip/repo/lwip/src/core/dns.c

Corrected a logic bug in LwIP’s dns_recv() function.  When processing a DNS response not containing any A or AAAA records, the code erroneously left the dns_table_entry in the DNS_STATE_ASKING state after alerting the user that the resolution had failed. Subsequently, when the DNS resolver timer (dns_tmr()) fired, code in dns_check_entry() would attempt to retry the request.  By this time, however, the UDP PCB associated with the dns_table_entry had been released, leading to a bad pointer dereference
The fix is to set the state to DNS_STATE_UNUSED after it has been determined that no further retries are possible.

Fix for Issue #124: TestDNSResolution: Seg fault in udp_sendto

---

src/inet/IPEndPointBasis.cpp

This is the first of two commits to address https://github.com/openweave/openweave-core/issues/130.

Ensure That mRaw and mUDP Usage in IPEndPointBasis Respect INET_CONFIG_ENABLE_{RAW,UDP}_ENDPOINT

---

src/lib/core/WeaveExchangeMgr.cpp
src/lib/core/WeaveExchangeMgr.h

This change reduces flooding of the Weave tasks' message queue on
NLER-based platforms in some circumstances. In NLER if a timer has
expired and posted its timer event but that event has not yet been
processed by the destination task (Weave task), and that timer is
then cancelled, the event will remain in the destination task's event
queue until the destination task dequeues it (and subsequently ignores
it, as it has been cancelled). This can lead to flooding of the message
queue by timer messages if we experince a burst of incoming traffic that
rapidly toggles the WRMP timer on and off. This is especially bad in
cases where we are overdue for a WRMP timer expiry, when every timer
toggle is an immediate expiry.

Only restart WRMP timer if needed

---

src/test-apps/happy/topologies/standalone/thread_wifi_on_tap_ap_service.json

Currently, the differences between the _src/test-apps/happy/topologies/standalone/thread_wifi_on_tap_ap_service.json_ and _src/test-apps/happy/topologies/standalone/thread_wifi_ap_service.json_ go beyond simply `tap: true` and `tap: false`, respectively. The former has different node addresses than the later. Since the Inet layer test has hard-coded addresses (itself a separate bug to be addressed), the Inet layer tests against LwIP can never work with the former topology (other issues notwithstanding).

Ensure Address Assignments Align between thread_wifi_*ap_service.json

---

src/test-apps/Makefile.am
src/test-apps/Makefile.in
src/test-apps/TestInetLayer.cpp
src/test-apps/TestInetLayerCommon.cpp
src/test-apps/TestInetLayerCommon.hpp
src/test-apps/happy/test-templates/WeaveInet.py
src/test-apps/happy/test-templates/WeaveInetMulticast.py
src/test-apps/happy/tests/standalone/inet/test_inet_01.py
src/test-apps/happy/tests/standalone/inet/test_inet_multicast_01.py

This fixes the Inet layer functional network test such that it works on both LwIP and sockets. In addition, it refactors it to use shared, common infrastructure code between it and the Inet layer multicast functional network test.

Fix Inet Layer Functional Network Test Such That it Works on Both LwIP and Sockets

---

src/tools/misc/virtual-ap.sh

virtual-ap.sh is a shell script that automates the process of setting up a Virtual WiFi access point on a linux system using an available WiFi interface.  virtual-ap.sh is intended to support the development and testing of WiFi-enabled IoT devices without the need for a dedicated access point.
virtual-ap.sh uses hostapd, dnsmasq and iptables to create a WiFi access point that provides DHCP and DNS services for attached clients.  Clients are granted access to external destinations via the host's primary interface, but only those with public IPv4 addresses; access to destinations with private (RFC-1918) addresses is blocked to improve security.  Access to the linux host itself is also blocked, with the single exception of the Weave port (11095).
Various command line options provide the …

virtual-ap.sh -- Tool to create a virtual WiFi AP on linux

---

src/device-manager/WeaveDeviceManager-JNI.cpp

Regression since 61384990c4; when the N2J_NetworkInfo method was updated to include the additional Thread network parameters, the order of parameters was incorrect. The Thread PAN ID was being supplied in place of the wireless signal strength, which frequently exceeds the limit of a jshort.

Fix a crash when decoding NetworkInfo from JNI

---

src/device-manager/WeaveDeviceManager.cpp
src/inet/IPAddress.cpp
src/inet/IPAddress.h
src/lib/core/WeaveFabricState.cpp
src/lib/core/WeaveMessageLayer.cpp
src/test-apps/TestInetAddress.cpp
src/test-apps/TestInetLayerMulticast.cpp
src/test-apps/TestWeaveFabricState.cpp

This enhances and extends the IPv6 multicast address creation APIs to cover additional address types such as transient and prefix addresses, renaming and creating an explicit API for well-known addresses in the process, the only type previously available.

Enhance and Extend IPv6 Multicast Address Creation APIs to Cover Additional Address Types

---

src/device-manager/WeaveDeviceManager.cpp
src/lib/core/WeaveConfig.h

Permits the transmission of old message directly.
Issue:
SAPPHIRE-18344
Change-Id: I0a36fc31102e678bdb2ab1309757240ec180c821

Enable exclusive use of legacy AddNetwork in WeaveDeviceManager

---

src/device-manager/WeaveDeviceManager-JNI.cpp
src/device-manager/java/src/nl/Weave/DeviceManager/TestMain.java
src/device-manager/java/src/nl/Weave/DeviceManager/WeaveDeviceDescriptor.java
src/device-manager/python/WeaveDeviceMgr.py
src/lib/profiles/device-description/DeviceDescription.cpp
src/lib/profiles/device-description/DeviceDescription.h
src/test-apps/TestWeaveDeviceMangerJNI
src/test-apps/test-weave-device-descriptor-encode.sh
src/test-apps/weave-device-descriptor.cpp

-- Extended WeaveDeviceDescriptor class with a new Flags field containing a single flag, (IsRendezvousWiFiESSIDSuffix) signaling that the RendezvousWiFiESSID field contains a
suffix string, rather than the entire ESSID string.
-- Modified the encode/decode methods for WeaveDeviceDescriptor to support device descriptors containing the new RendezvousWiFiESSIDSuffix tag/text key.
-- Updated the WeaveDeviceDescriptor wrapper classes for Java and Python to support the ESSID suffix field.
-- Modified the weave-device-descriptor command line tool to support encoding and decoding
device descriptors containing an ESSID suffix.
-- Added a unit test to the test-weave-device-descriptor-encode.sh test script.
-- Extended NLWeaveDeviceDescriptor interface with support for IsRendezvousWiFiESSIDSuffix …

Issue 142 : Add support for Rendezvous WiFi ESSID Suffix to Device Descriptor

---

src/lib/profiles/data-management/Current/NotificationEngine.cpp
src/lib/profiles/data-management/Current/SubscriptionClient.cpp
src/lib/profiles/data-management/Current/SubscriptionClient.h
src/lib/profiles/data-management/Current/SubscriptionEngine.cpp
src/lib/profiles/data-management/Current/SubscriptionHandler.cpp
src/lib/profiles/data-management/Current/TraitCatalog.h
src/lib/profiles/data-management/Current/ViewClient.cpp
src/test-apps/TestTDM.cpp

Redesign the way elements are removed. Instead of erasing an element from the catalog,
only set trait pointer to NULL, so DataHandle order would remain always the same.

Redesign how TraitCatalog is keeping elements.

---

third_party/lwip/repo/lwip/src/core/memp.c

This is a fix for TOPAZ-6525. When the queue was full the sys_profile_interval_set_pbuf_highwatermark() recorded a number of bytes in the element instead of elements count.

Recording watermark by pbuf when queue is full fix

---

src/lib/profiles/weave-tunneling/WeaveTunnelAgent.cpp
src/test-apps/TestWeaveTunnel.h
src/test-apps/TestWeaveTunnelBR.cpp

Fix for Issue #172 
This was being achieved by the routingRestricted flag sent in the
StatusReport in response to the TunnelOpen. Instead, the
WeaveTunnelAgent should consult its configured role(Standalone) to
disable platform-level border gateway function.

Standalone Tunnel establishment should disable border gateway configuration at the platform level.

---

.travis.yml
.travis/before_install.sh
.travis/script.sh

This pull request adds LwIP-based network and service tests to the Travis continuous integration matrix.

Add LwIP-based Network and Service Tests

---

src/test-apps/happy/test-templates/WeaveInetDNS.py
src/test-apps/happy/tests/standalone/inet/test_inet_dns_01.py

1. Removed code that disabled the Inet DNS test on LWIP
2. Fixed typos in WeaveInetDNS init part -- the existing code passed some attributes to an irrelevant dictionary

enable inet dns test for lwip

---

.travis.yml
.travis/script.sh

I've got artifacts work with gcs using travis-ci interface, PR is:
https://github.com/openweave/openweave-core/pull/182
I have tested on my repo, here is the link of test logs upload example on gcs:
https://pantheon.corp.google.com/storage/browser/openweave/happy-test-log/164/?project=openweave-test-project&authuser=0&organizationId=433637338589
I've enabled it for all branches, so it should upload logs automatically to gcs from PR branch as well.
Hope this effort will help debugging the test flakiness on travis-ci.
Please let me know if you have any questions.
Note: Content in .travis.yml got shift to front a little bit, that is done by command "travis setup gcs" during travis-ci/gcs setup, more info is in this link:
https://docs.travis-ci.com/user/deployment/gcs/

artifact support to get both lwip and linux-auto logs to gcs

---

src/lib/core/WeaveMessageLayer.cpp
src/lib/profiles/data-management/Current/TraitData.cpp
src/lib/profiles/data-management/Current/UpdateClient.cpp
src/lib/support/WeaveFaultInjection.cpp
src/lib/support/WeaveFaultInjection.h
src/test-apps/happy/tests/service/wdmNext/test_weave_wdm_next_service_update_faults.py

Make sure that while processing the DataList in a Notify starting from
the root, filter checks are correctly performed while descending into
dictionaries and DictionaryReplace/Modify pre-processing functions
are not called for dictionary paths that also exist in a pending WDM
Update.

Fix for WEAV-3231.

---

src/tools/weave/Cmd_GenCodeSigningCert.cpp
src/tools/weave/KeyUtils.cpp
src/tools/weave/weave-tool.h

In order to store firmware leaf key material in an HSM, I need to generate the private keys in a secure environment and sign only the public key. Adding the functionality to do so in weave tool.

Adding ability to create firmware signing leaf from public key

---

src/lib/profiles/data-management/Current/SubscriptionHandler.cpp
src/lib/profiles/data-management/Current/SubscriptionHandler.h
src/lib/support/PersistedCounter.cpp
src/lib/support/PersistedCounter.h

Weave provides to the application the event ids send down as part of the
subscription request.
A new method is added to PersistentCounter that allows the counter to be
advanced past a given value (event id).

Give event ids from subscription request to the app

---

src/lib/profiles/service-directory/ServiceDirectory.cpp
src/lib/profiles/service-directory/ServiceDirectory.h

The previous `lookup` method was not terribly useful -- it exposed the
internal structures in the ServiceDirectory, and it was not entirely
clear how to use it properly.  This commit refactors the code such
that:
* we provide a variant of the `lookup` method that populates a
HostPortList.
* we use the code internally to implement the code paths inside
`lookupAndConnect`

Enhance the API of the ServiceDirectory to produce a HostPortList

---

src/adaptations/device-layer/ServiceProvisioningServer.cpp
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/ServiceProvisioningServer.h

-- Before a pair device to account request can be sent out, the service
provisioning server would check to see if a tunnel has been established
with the service. Service Provisioning would always fail on platforms
such as the nRF5 since it doesn't have the capability to establish a tunnel
directy with the service.
-- Solution: Add logic to gate the provisioning request only when service
connectivity AND service tunnel connection have NOT been established.

Fixed a bug in ServiceProvisioningServer that was causing timeouts.

---

src/test-apps/happy/tests/standalone/wdmNext/test_weave_wdm_next_mutual_subscribe_faults.py

Previous pull request added a new fault label for testing a particular scenario around WDM Update in the presence of faults.  This label needs to be added to the "not_required_server_faults" set in the scripts to ensure proper function. The fault injection tests are currently not a part of GitHub pull request validation, as at the moment they are too time consuming.

fix internal fault injection test fail CIEC-3526

---

Makefile-Standalone

The compilation flag -maes is applicable only to x86_64 processors that support AES-NI instructions. Use the flag only in that context.
Switch to using uname -m to determine the machine architecture. This call is POSIX-postable, whereas uname -i and uname -p are non-portable and produce unexpected results on Linux ARM, Mac OS x86_64, etc.

Properly conditionalize the use of -maes option

---

src/ble/BleError.cpp
src/inet/InetError.cpp
src/system/SystemConfig.h
src/system/SystemError.cpp

The new logging formatting code decentralized error formatting:
different Weave sub-libraries -- WeaveSystem, Inet, Warm -- now
provide their own error formatting.  Within Weave, however, it is
desirable to have a single config flag that switches between short and
verbose error codes.  To that end, we retain the control over the
logging format via WEAVE_CONFIG_SHORT_ERR_STRING, and to ensure the
propagation of that define into appropriate modules, we include the
config headers that could impact the value of that define in the
SystemConfig.h.
Include <stddef.h> in the new error formatter files, to ensure that
NULL is defined.

Fixes to the new logging configuration

---

src/device-manager/cocoa/NLWeaveDeviceDescriptor.h
src/device-manager/cocoa/NLWeaveDeviceDescriptor.mm

Add property IsRendezvousWiFiESSIDSuffix that denotes whether the
RendezvousWiFiESSID  is a suffix or not.

Add support for Rendezvous WiFi ESSID Suffix ot ObjC API

---

src/lib/profiles/weave-tunneling/WeaveTunnelConnectionMgr.cpp

Fix typo(extraneous %s) in Tunnel logging when resetting Reconnect backoff.

Remove extraneous '%s' in logging format specifier in WeaveTunnelConnectionMgr.cpp.

---

src/adaptations/device-layer/DeviceDescriptionServer.cpp
src/adaptations/device-layer/include/Weave/DeviceLayer/ConnectivityManager.h
src/adaptations/device-layer/include/Weave/DeviceLayer/ESP32/ConnectivityManagerImpl.h
src/adaptations/device-layer/include/Weave/DeviceLayer/WeaveDeviceConfig.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/DeviceDescriptionServer.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericConnectivityManagerImpl.h
src/adaptations/device-layer/include/Weave/DeviceLayer/nRF5/ConnectivityManagerImpl.h
src/include/Makefile.am
src/include/Makefile.in

-- Implemented support in the Device Layer for User Selected Mode.
User Selected Mode is a feature of the Weave Device Identify protocol. When a device is placed in User Selected Mode, it will respond to Device Identify requests that have the UserSelectedMode flag set.  A device not in User Selected Mode will ignore such requests. User Selected Mode is typically initiated by a button press or some other form of direct user interaction.  The User Selected Mode feature allows a client, be it a mobile application or another device, to quickly identify a device that has been singled out by the user.  A device will automatically deactivate User Selected Mode after a configurable period of time.  Alternatively, the mode can be expressly deactivated by the application.
Since device UI is the …

Device Layer: Support for User Selected Mode

---

src/device-manager/cocoa/NLNetworkInfo.h
src/device-manager/cocoa/NLNetworkInfo.mm

constexpr is not available in Objective-C, only Objective-C++
Using the older form of constness allows this file to be directly imported by Objective-C sources

Make header importable by Objective-C source files

---

src/adaptations/device-layer/nRF5/nRF5Config.cpp
src/lib/support/NonProductionMarker.cpp

Eliminated a couple of warnings when building OpenWeave for the nRF5 SDK.

Fix for warnings

---

.travis/prepare_nrf52840.sh
build/nrf5/nrf5-app.mk
build/nrf5/nrf5-openthread.mk
src/adaptations/device-layer/include/Weave/DeviceLayer/OpenThread/GenericThreadStackManagerImpl_OpenThread_LwIP.ipp

-- Updated OpenWeave Device Layer to work with version 3.0 of the Nordic nRF5 SDK for Thread.
-- Modified Device Layer to work with later versions of the OpenThread API.
-- Added logic to nrf-app.mk to check for a minimum required version of the nRF5 SDK.

Update to version 3.0 of the Nordic nRF5 SDK

---

src/adaptations/device-layer/ESP32/Logging.cpp
src/adaptations/device-layer/include/Weave/DeviceLayer/WeaveDeviceConfig.h
src/adaptations/device-layer/nRF5/Logging.cpp

-- Added Device Layer config option to size the temporary buffer used to hold log messages during logging.
-- On nRF5 platforms, eliminated unnecessary multiple inclusions of nrf_log.h.
-- On nRF5 platforms, don’t use NRF_LOG_PUSH() if not using deferred logging.
-- Other minor editorial changes.

Various changes to Device Layer logging

---

src/adaptations/device-layer/DeviceControlServer.cpp

-- Fixed a cut-and-paste error in the Device Layer’s implementation of DisarmFailSafe that resulted in the fail-safe not being disarmed.

Fixed bug in DisarmFailSafe

---

.travis/before_install.sh
.travis/script.sh
Makefile-Standalone
build/nrf5/nrf5-app.mk

-- Revised Makefile-Standalone to automatically detect and use the standard OpenSSL package installed on either Linux or OS X, when available.  On Linux, the logic uses pkg-config to determine if the standard OpenSSL development package (typically libssl-dev) has been installed.  On OS X, the logic uses homebrew to look for the OpenSSL formula.  If a standard package is not detected, the build falls-back to using the internal version of OpenSSL located in third_party/openssl.
-- Added OPENSSL argument to Makefile-Standalone that allows the developer to override the above logic.
-- Updated Travis build script for OS X to use Makefile-Standalone, rather that calling configure and make directly.
-- Added prebuild steps to Travis OS X builds to install homebrew packages for openssl, automake …

Clean up build support for OS X

---

src/lib/profiles/echo/Current/WeaveEchoClient.cpp

One of the fault injection tests was failing on weave-ping in a case
where a WRMP echo request was responded to but not acknowledged.  The
proper behavior for the echo client is to abort the exchange (which
implies not worrying about the pending retransmissions) when the valid
echo response was received and there is no pending action on a WRMP
ack.

Fix a delayed resource deallocation

---

src/test-apps/Makefile.am
src/test-apps/Makefile.in
src/test-apps/weave-parallel-test-engine

The changes in this commit add a PID-based prefix to all happy tests
run within a particular instance of the build.  This enables a
non-conflicting way to run multiple simultaneous execution of Weave
tests on the same machine, as the "happy" simulator instances are
non-overlapping.

Group test instances run within happy by PID of the makefile

---

src/lib/profiles/bulk-data-transfer/BulkDataTransfer.h
src/lib/profiles/data-management/Current/EventLoggingTypes.h
src/lib/profiles/data-management/Current/LoggingManagement.h
src/lib/profiles/data-management/Current/MessageDef.h
src/lib/profiles/data-management/Current/SubscriptionClient.cpp

These were flagging as typos in the openweave.io reference update, so fixing at the source.

Fix typos in Doxygen comments

---

src/lib/profiles/data-management/Current/LoggingManagement.cpp
src/test-apps/MockLoggingManager.cpp
src/test-apps/MockLoggingManager.h
src/test-apps/TestEventLogging.cpp
src/test-apps/TestWdmNext.cpp

The logging system treats the counter value `0` as special. We change
the starting value of non-persistent counters to `1`, and modify the
unit tests to reflect this assumption in the code.
This change also enabled us to remove the entire call chain to enable
an option to initialize the event IDs based on the timestamp.

Changed the initial value of the non-persistent logging counters.

---

CONTRIBUTING.md
doc/STYLE_GUIDE.md
doc/guides/cross-network-inet-multicast-howto.md

Also:
- updated CONTRIBUTING.md to cover documentation
- moved the Cross Network HOWTO to a new "guides" directory under docs
- minor revisions to the Cross Network HOWTO for 1) formatting so it can be more easily mirrored on openweave.io and 2) style to adhere to Google Developers style
Fixes #256

Add documentation style guide

---

src/device-manager/WeaveDeviceManager-JNI.cpp
src/device-manager/java/src/nl/Weave/DeviceManager/WeaveDeviceDescriptor.java
src/lib/profiles/device-description/DeviceDescription.cpp

Expose pairing compatibility major and minor versions in Java to bring
it into parity with Objective C code.  While reviewing decoding logic
in the device descriptor, we noticed that the behavior was not
consistent w.r.t. clearing the device descriptor; now all Decode*
methods clear the output descriptor.

Expose pairing compatibility major and minor versions in Java code

---

src/test-apps/happy/lib/WeaveTest.py
src/test-apps/weave-parallel-test-engine

Made changes based on discussion with @robszewczyk today:
This PR will need one happy PR below as pre-requisition:
https://github.com/openweave/happy/pull/31
changes related in this PR:
a. get hold of HAPPY_LOG_DIR in environment variable in weave-parallel-test-engine
b. the persistent log file is handled in WeaveTest.py

organize test log

---

.travis/script.sh

Given the changes from openweave-core PR#265 and happy PR#31 happy no longer puts the logs in /tmp and thus the copying logs from /tmp is no longer required.

remove copy log from tmp

---

src/device-manager/cocoa/NLWeaveDeviceDescriptor.mm

We are allocating twice the memory needed to buffer the QR code string. The second allocation, in strdup, is overwriting the assignment of the pointer to the first. Consequently, the first allocation is never free'd. In the end, we don't need to allocate anything ourself and can defer to Apple's Foundation to do that for us.

Corrected memory leak from extra allocation.

---

src/test-apps/TestInetAddress.cpp

A set of unit tests used addresses that had multiple representations:
addresses with `:0:` quad in them could be also be represented with
`::`.  On a number of Mac OS machines, the underlying library call has
been emitting the `::` notation, breaking tests.  We modify the tests
to avoid the problem.

Make the nl::Inet::IPAddress tests more robust

---

src/test-apps/happy/tests/standalone/inet/test_inet_dns_01.py
src/test-apps/happy/tests/standalone/inet/topology/two_nodes_wifi.sh

use different shell script to create topology for tap device and non-tap device
tested one another branch, result is here:
https://travis-ci.org/openweave/openweave-core/builds/556519764
To fix issue: https://github.com/openweave/openweave-core/issues/297

fix inet dns test

---

src/lib/profiles/security/X509ToWeave.cpp

Replaced kTag_SubjectKeyIdentifier_Critical with kTag_KeyUsage_Critical
when converting Key Usage Extension.
This is not a functional bug because both enums have the same value "1".

Fixed Typo In The ConvertExtension() Function.

---

src/adaptations/device-layer/ESP32/BLEManagerImpl.cpp
src/adaptations/device-layer/include/Weave/DeviceLayer/ConfigurationManager.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericConfigurationManagerImpl.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericConfigurationManagerImpl.ipp
src/adaptations/device-layer/nRF5/BLEManagerImpl.cpp
src/ble/WeaveBleServiceData.h
src/include/Makefile.am
src/include/Makefile.in

-- Corrected a mistake in the encoding of the Weave BLE device identification block that gets sent as BLE service advertisement data by the nRF52840.  The previous version of the code omitted two fields, which caused considerable heartburn for the Nest mobile application.
-- Corrected another minor mistake in the encoding of the device identification block on the ESP32 which resulted in the wrong data block type being sent.  This bug didn’t seem to bother the mobile application.
-- Created a common data structure for encoding and decoding a Weave BLE device identification block and refactored the nRF5 and ESP32 code bases to use this structure.

Fix for Issue #283: Invalid Weave BLE scan response from nRF5 Device Layer

---

src/adaptations/device-layer/include/Weave/DeviceLayer/OpenThread/GenericThreadStackManagerImpl_OpenThread.h
src/adaptations/device-layer/include/Weave/DeviceLayer/OpenThread/GenericThreadStackManagerImpl_OpenThread.ipp
src/adaptations/device-layer/include/Weave/DeviceLayer/ThreadStackManager.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericConfigurationManagerImpl.ipp

On Nordic, populate 802.15.4 extended address. This address may be a
meaningless set of numbers -- there is no guarantee that the address
populated will be the same as the address used in joining (or
re-attaching) to any particular Thread network or that it will
correspond to the factory provisioned EUI64.

Populate 802.15.4 MAC address on Nordic

---

.travis.yml
.travis/after_failure.sh

Hi @gerickson @jaylogue @robszewczyk :
This is the PR to address issue of "not uploading logs after test failure", please help to review.
I have tested it on one of my test branch, which I did return value 2 by intention to make test fail everytime:
https://github.com/openweave/openweave-core/tree/lwip_upload_fail_log
result link for test branch when test failedis:
https://travis-ci.org/openweave/openweave-core/builds/557980883
Thanks
Jennie

upload logs to gcs after failure

---

src/test-apps/happy/test-templates/WeaveServiceDir.py
src/test-apps/happy/tests/standalone/servicedir/test_service_directory_01.py
src/test-apps/happy/topologies/standalone/thread_wifi_ap_service.sh
src/test-apps/happy/topologies/standalone/thread_wifi_on_tap_ap_service.sh

Hi Jay/RS:
Based on last week's meeting, I've made changes to service-dir lwip test and tested at my local for both lwip and socket case, test passed in both cases in my local test.
Please help to review the code.
BTW: This will need another small PR from Happy, which will remove IP assignment if device is a tap device.
https://github.com/openweave/happy/pull/35

enable service-dir lwip tests

---

build/nrf5/nrf5-app.mk

-- Add the ability to specify the J-Link probe serial number on the make command line when flashing or erasing a Nordic device.  This makes it possible to select from multiple boards connected to the same host.
The target serial number is specified as follows:
```
make JLINK_SN=609303305 flash-app
```

Support for J-Link serial number argument

---

src/test-apps/Makefile.am
src/test-apps/Makefile.in
src/test-apps/MockWdmNodeOptions.cpp
src/test-apps/MockWdmNodeOptions.h
src/test-apps/MockWdmSubscriptionInitiator.cpp
src/test-apps/MockWdmSubscriptionResponder.cpp
src/test-apps/happy/test-templates/WeaveWdmNext.py
src/test-apps/happy/tests/standalone/wdmNext/test_weave_wdm_next_update_01.py
src/test-apps/happy/tests/standalone/wdmNext/test_weave_wdm_next_update_02.py
src/test-apps/happy/tests/standalone/wdmNext/test_weave_wdm_next_update_03.py

-- add wdm conditional update integration test and unconditional update integration
test along with subscription.
-- add standalone wdm unconditional integration test without
subscription.
-- remove smoke check for wdm test since we should only rely on the log-check
in test application script, and reduce the log check confusion.
-- add NoSub enum value in WdmUpdateTiming, currently it include before
sub, during sub, and after sub, possibly it is good place to add no sub.
-- during no sub, MonitorClientCurrentState would be triggered when all
update iteracton completes.
-- with sub, update shutdown would be handled in existing sub shutdown
codepth.
-- delete the dead code in MockWdmSubscriptionInitiator.cpp and
MockWdmSubscriptionResponder.cpp.

add wdm update integration tests

---

Makefile-Standalone

Homebrew is not always installed in /usr/local. This use standard way to
get Homebrew's prefix.

Support brew prefix not equal to /usr/local

---

src/adaptations/device-layer/include/Weave/DeviceLayer/ConnectivityManager.h
src/adaptations/device-layer/include/Weave/DeviceLayer/OpenThread/GenericThreadStackManagerImpl_OpenThread.h
src/adaptations/device-layer/include/Weave/DeviceLayer/OpenThread/GenericThreadStackManagerImpl_OpenThread.ipp
src/adaptations/device-layer/include/Weave/DeviceLayer/ThreadStackManager.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericConnectivityManagerImpl_NoThread.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericConnectivityManagerImpl_Thread.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericPlatformManagerImpl.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericPlatformManagerImpl.ipp
src/lib/core/WeaveMessageLayer.cpp
src/lib/core/WeaveMessageLayer.h

-- Added APIs to the Device Layer’s ConfigurationManager object to control the Thread device type on Thread-enabled platforms.  Four standard Thread device types are supported: Router, Full End Device, Minimal End Device and Sleepy End Device.
-- Added APIs to the ConfigurationManager object to control polling behavior on devices that are operating as Thread sleepy end devices.  Two distinct polling intervals are configurable: one for when the device is engaged in active Weave message exchanges and one for when the device is idle.
-- Extended the following generic implementation classes to support the above APIs: GenericThreadStackManagerImpl_OpenThread<>, GenericConnectivityManagerImpl_Thread<> and GenericConnectivityManagerImpl_NoThread<>.
-- Added IsMessageLayerActive() method to the …

Device Layer support for Thread device type and polling control

---

doc/general/weave-factory-provisioning-tool.md
src/tools/factory-prov-tool/WeaveFactoryProvisioningTool.py

-- Created overview documentation for the OpenWeave factory provisioning tool describing its theory of operation and its user interface.
-- Enhanced the factory provisioning tool to allow any provisioning value to be specified in a provisioning data CSV file.  This means that the supported CSV file format is a now superset of that produced by the weave tools’s “gen-provisioning-data” command.
-- Renamed the default CSV column names to use underscores instead of spaces.  Note that the provisioning tool is still backwards compatible with CSV files using the old format column names.

Documentation for factory provisioning tool, plus minor feature enhancements

---

src/adaptations/device-layer/EventLogging.cpp
src/lib/core/WeaveEventLoggingConfig.h

-- Remove definition of CriticalSectorEnter and Exit methods
from EventLogging.cpp so that application can define them
as required.
This fixes an issue where the notification engine while gathering wdm
events was waiting indefinitely for the weave stack lock to be
acquired since it was already locked when the event loop on the weave
task ran to handle the notification run asynchronous request.

Support for publishing wdm events

---

src/adaptations/device-layer/include/Weave/DeviceLayer/SoftwareUpdateManager.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericSoftwareUpdateManagerImpl.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericSoftwareUpdateManagerImpl.ipp

-- No need to track if software update was aborted in a separate
variable. Instead test if the internal state is the expected state
right after we return from an event callback.
-- Rename kAction_Defer_To_Application to kAction_ApplicationManaged in
the SoftwareUpdateManager public interface

Minor code cleanup in GenericSoftwareUpdateManagerImpl

---

src/test-apps/happy/topologies/standalone/thread_wifi_on_tap_ap_service.json

In PR https://github.com/openweave/openweave-core/pull/295, we fixed the [topology shell script ](https://github.com/openweave/openweave-core/pull/295/files?file-filters%5B%5D=.sh#diff-bc7d815637b60f39bb32ae8ad76c6579) to work with lwip tests, I did not update topology json file because not sure if it will break other tests.
As separate follow up PR, I copied .happy_state.json which generated by src/test-apps/happy/topologies/standalone/thread_wifi_on_tap_ap_service.sh to replace thread_wifi_on_tap_ap_service.json, so that json topology file content is consistent with it's shell script.
From the commit comparison, there is weave cert config not covered by shell script, Will see if it can pass the CI tests first.

fix thread_wifi_on_tap_ap_service.json to be consistent as its shell script

---

doc/general/weave-factory-provisioning-tool.md
src/lib/core/WeaveMessageLayer.h
src/tools/factory-prov-tool/WeaveFactoryProvisioningTool.py

Historically Weave NodeIds have always been universal (globally unique) identifiers.
Therefore, it was sufficient to set or clear the Universal/Local (U/L) bit when converting
WeaveNodoId to IPv6InterfaceId and vise versa.
In preparation for supporting also local identifiers this implementation has
been updated to invert U/L bit when converting, per RFC-3513.

Updated IPv6InterfaceId to WeaveNodeId Conversion Functions.

---

src/device-manager/cocoa/NLProfileStatusError.mm
src/device-manager/cocoa/NLWeaveDeviceManagerTypes.h

Add translated error constant for `nl::Weave::Profiles::Common::kStatus_AccessDenied` to the objc device-manager.
This constant is needed for Nest app error routing.

Make kStatus_AccessDenied visible from objc device-manager.

---

src/adaptations/device-layer/DeviceNetworkInfo.cpp
src/device-manager/cocoa/NLNetworkInfo.h
src/device-manager/cocoa/NLNetworkInfo.mm
src/device-manager/java/WeaveDeviceManager-JNI.cpp
src/device-manager/java/src/nl/Weave/DeviceManager/NetworkInfo.java
src/device-manager/python/openweave/WeaveDeviceMgr.py
src/device-manager/python/weave-device-mgr.py
src/lib/profiles/network-provisioning/NetworkInfo.cpp
src/lib/profiles/network-provisioning/NetworkInfo.h
src/lib/profiles/network-provisioning/NetworkProvisioning.h
src/test-apps/MockNPServer.cpp
src/test-apps/TestNetworkInfo.cpp

This change allow users to set PSKc in network provisioning.
PSKc is used to authenticate thread commissioner. The unimplemented
part of PSKc configuration is completed.

[Thread] add thread pskc to network provisioning

---

src/device-manager/java/src/nl/Weave/DeviceManager/TestMain.java
src/test-apps/wrapper-tests/jni/src/WeaveKeyExportClientTest.java

java.xml.bind.DataTypeConverter has been deprecated in Java 9 and
removed in Java 11.  Our usage was minimal and limited to test code,
so we replace two methods from the DataTypeConverter --
`printHexString` and `parseHexString` with naiive implementations.

Remove references to java.xml.bind.DataTypeConverter

---

src/test-apps/Makefile.am
src/test-apps/Makefile.in

It appears that Travis CI no longer supports the BLE-based tests --
the tests fail to start the Bluetooth daemon, the daemon fails with:
00:24:42.194097 socket(PF_BLUETOOTH, SOCK_RAW, 1) = -1 EAFNOSUPPORT (Address family not supported by protocol)
We are disabling the test until such time as we have a suitable
workaround.

Remove the failing pairing/test_weave_ble_01.py test

---

src/adaptations/device-layer/LwIP/WarmSupport.cpp
src/adaptations/device-layer/include/Weave/DeviceLayer/LwIP/WarmSupport.h

[ This change addresses the following issue: [issue#10](https://github.com/openweave/openweave-esp32-demo/issues/10) ]
-- Added code to the LwIP-specific WARM code within the Device Layer such that a device joins/leaves the appropriate IPv6 solicited-node multicast group whenever Weave IPv6 addresses are added/removed from the device's network interfaces.  Although LwIP has logic to do this automatically, when the LWIP_IPV6_MLD LwIP feature is enabled, this behavior is tightly bound to duplicate address detection, which is not invoked by the WARM layer.

Fix for ESP32 demo app not responding to IPv6 neighbor discovery

---

src/test-apps/happy/lib/WeaveNodeConfigure.py
src/test-apps/happy/lib/WeaveState.py
src/test-apps/happy/topologies/standalone/thread_wifi_on_tap_ap_service.sh

In lwip service tunnel test 02, we do weave-ping test between thread node and service(cloud) node, which will require both thread node and service node to have weave address.
This PR is to fix 2 minor issues that:
1. weave test infra does not add weave address if it is a service node.
2. node interface type for service node should be "wan", without correct interface type, service node is not getting correct weave address subnet.

minor fix to support weave address on service node

---

src/device-manager/WeaveDeviceManager.cpp
src/device-manager/WeaveDeviceManager.h
src/device-manager/python/WeaveDeviceManager-ScriptBinding.cpp
src/device-manager/python/openweave/WeaveDeviceMgr.py
src/device-manager/python/weave-device-mgr.py
src/inet/IPEndPointBasis.cpp

Enabled an additional `rendenzvousIntf` parameter in
WeaveDeviceManager::SetRendezvousAddress so that the Identify messages
can be sent on a specific interface.  Currently the plumbing is
enabled for Python only.  The change required re-enabling older
codepaths that would use `sendmsg` instead of `sendto`.

Enable interface selection in rendezvous and device enumeration

---

src/lib/profiles/data-management/Current/UpdateClient.h

Clang 9 emits a warning on an anonymous empty union.  In UpdateClient,
the OutEventParams declared no specific parameters which resulted in
the above construction.  Replace the problematic construct with a note
to the future developer on how to extend the parameters.

Clang 9 warning fix.

---

src/lib/profiles/weave-tunneling/WeaveTunnelConnectionMgr.cpp
src/test-apps/TestWeaveTunnelBR.cpp

When the reconnect timer fires, ensure that the WeaveConnectionManager is in the correct 'NotConnected' state before attempting the reconnect.
Previously, there was only a check and exit if the state was wrong.

Ensure WeaveTunnelConnectionManager is in correct state before trying to reconnect when timer fires.

---

src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericConfigurationManagerImpl.ipp

-- Instead of signed decimal integer format, use unsigned decimal
integer format specifier when printing the Vendor Id

Fix format specifier for vendor Id

---

src/adaptations/device-layer/nRF5/BLEManagerImpl.cpp

[ This change addresses b/140955318. ]
-- Fixed a logic bug in ConnectivityManager::SetBLEAdvertisingEnabled() where passing false would not actually stop BLE advertising.
-- Added log message when BLE advertising stopped.

Fixed bug in nRF52 ConnectivityManager::SetBLEAdvertisingEnabled()

---

src/tools/simnet/simnet.py

-- Fixed bug in simnet tool that resulted in the 'shell' command failing when linux
decided to assign ids to network namespaces.  This caused a change in the output
of the 'ip netns list' command which simnet wasn't prepared to parse.

Fixed bug in simnet 'shell' command

---

src/tools/simnet/lib/simnet/layouts/two-devices.py
src/tools/simnet/simnet.py

-- Fixed support for tap interfaces within virtual nodes.  Unlike a veth-pair, the two ends of a linux tap device cannot be in different namespaces.  To make it possible for a tap interface in a node namespace to be connected to bridge in a “network” namespace, simnet now constructs a “trunk line” veth-pair that spans the two namespaces, and a “tap bridge” in the node namespace.  The tap interface is connected to the tap bridge, along with one of the trunk interfaces.  The other trunk interface is connected to the bridge in the “network” namespace.  This allows packets to flow between the process holding the tap fd and the virtual network.
-- Eliminated the use of special short interface names when creating tap interfaces.  These interfaces now use the names “wifi”, “thread”, etc., just …

Yet more fixes to simnet

---

src/tools/weave/Cmd_ConvertProvisioningData.cpp

Corrected small logic bug in the weave tool's convert-provisioning-data command.

Fix for Issue#388 : weave convert-provisioning-data command double encodes output

---

src/device-manager/python/build-openweave-wheel.py

Allow the openweave python package version to be set from OPENWEAVE_PYTHON_VERSION when the package is built outside of Travis CI

Update openweave python package versioning

---

doc/STYLE_GUIDE.md
doc/guides/tools/index.md

- Changes method of designating Material Icons in docs to use HTML comments
- Adds complete Material Icon support for docs mirrored on openweave.io, in preparation for migrating the Weave Primer to GitHub
- Updates current usage of Material Icons in the Tools index to the new format

Complete Material Icon support for docs

---

src/tools/simnet/simnet.py

-- Insert rather than append the iptables rules that redirect packets to the simnet sn-FORWARD table.  This ensures packets flow through the simnet rules before any system firewall rules installed in the host namespace.

Fixed bug in simnet when installing iptables rules in the host namespace

---

src/adaptations/device-layer/include/Weave/DeviceLayer/OpenThread/GenericThreadStackManagerImpl_OpenThread.ipp
src/adaptations/device-layer/nRF5/BLEManagerImpl.cpp

Don't start Thread radio until Weave pairing has set the Thread credentials.
Also fixes an assert in WoBLE peripheral timeout when connection has already been closed.

[toble] Fix ble pairing conflicts with thread

---

src/tools/factory-prov-tool/WeaveTLV.py

-- Fixed a bug in the Python TLVWriter implementation caused all instances of the class to use the same output buffer.

Fix for bug in Python TLVWriter

---

src/inet/InetInterface.cpp

-- Added missing LwIP header to InetInterface.cpp.  Apparently this header gets included via some other path in the standalone LwIP build.

Fix compile failure in lock example

---

src/adaptations/device-layer/include/Weave/DeviceLayer/WeaveDeviceConfig.h
src/adaptations/device-layer/nRF5/BLEManagerImpl.cpp

Provides an option to disable WoBLE advertisements while a WoBLE connection is active.

[woble] Add single BLE connection option. 

---

src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericSoftwareUpdateManagerImpl_BDX.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericSoftwareUpdateManagerImpl_BDX.ipp

Fix for [Issue#412](https://github.com/openweave/openweave-core/issues/412) : ExchangeContext leak when BDX download fails during software update
Fix for [Issue#413](https://github.com/openweave/openweave-core/issues/413) : BDXTransfer object leaked during software update
-- Restructured GenericSoftwareUpdateManagerImpl_BDX<> such that it properly cleans up allocated resources when an image download completes, successfully or otherwise.  This eliminates leaking an exchange context, a BDXTransfer object and/or a Binding object, depending on the circumstances.

Fix leaks in software update

---

src/ble/BLEEndPoint.h
src/ble/BleLayer.cpp

Force alignment of both PoolElement and sEndPointPool to ensure that returned BLEEndPoints are 8-byte aligned

(Issue #416) Ensure 8B alignment of BLEEndpoints

---

src/adaptations/device-layer/ESP32/BLEManagerImpl.cpp
src/adaptations/device-layer/include/Weave/DeviceLayer/ConnectivityManager.h
src/adaptations/device-layer/include/Weave/DeviceLayer/ESP32/BLEManagerImpl.h
src/adaptations/device-layer/include/Weave/DeviceLayer/WeaveDeviceEvent.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/BLEManager.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericConnectivityManagerImpl_BLE.h
src/adaptations/device-layer/include/Weave/DeviceLayer/nRF5/BLEManagerImpl.h
src/adaptations/device-layer/nRF5/BLEManagerImpl.cpp

- Introduced a new WoBLEAdvertisingChange device event that gets generated whenever the BLEManager starts and stops WoBLE advertising.
- Added method to ConnectivityManager to determine whether WoBLE advertising is currently active.
- Fixed logic bugs in the transition between fast and slow WoBLE advertising.  The system will now properly transition between the two modes when the device’s provisioning state changes, or when expressly asked to by the application.
- Eliminated subtle race condition on Nordic platforms where WoBLE would be disabled entirely due to an unexpected error from the SoftDevice if a connection arrived just as the BLEManager was updating the advertising configuration.
- Renamed BLEManager internal flag values and added documentation to make their meaning clearer.

BLEManager changes

---

src/lib/core/WeaveExchangeMgr.cpp
src/lib/profiles/data-management/Current/LoggingManagement.cpp
src/lib/profiles/device-description/DeviceDescription.cpp
src/lib/profiles/weave-tunneling/WeaveTunnelConnectionMgr.cpp
src/ra-daemon/RADaemon.cpp

This fixes a compiler warning in gcc 8+. That compiler now warns when
calling memset writes to private variables in a struct. This appears
to mostly be the cause of the warnings here.

Use default-construct and assign for some variables

---

src/lib/profiles/time/WeaveTime.h
src/lib/profiles/time/WeaveTimeClient.cpp

Based on the feedback from @lcniles, this patch cleans up a logic bug
in WeaveTimeClient.  WeaveTimeClient has a notion of "normal" state, I
ended up adopting "operational" state as the term.  The term denotes
all possible states that are not a part of initialization or shutdown
of the module.  This PR defines the canonical helper function,
replaces the faulty logic in `HandleTimeChangeNotification`, and
cleans up the correct but confusing logic in `Abort`.

Fix a logic bug and perform minor cleanup

---

src/adaptations/device-layer/include/Weave/DeviceLayer/nRF5/BLEManagerImpl.h

- Added accessor functions to the Nordic version of the BLEManagerImpl class that allow the application to get and set the SoftDevice BLE advertising handle.

Accessor functions for SoftDevice advertising handle

---

src/adaptations/device-layer/ESP32/BLEManagerImpl.cpp
src/adaptations/device-layer/include/Weave/DeviceLayer/ESP32/BLEManagerImpl.h

- Fixed a set of logic bugs in the ESP32 version of the BLEManager having to do with refreshing the WoBLE advertising state as the state of the device changes.  These bugs were inadvertently introduced in the previous change to this code.

Fixed logic bugs in ESP32 BLEManager

---

src/inet/InetInterface.cpp

Included header is unused (provides, by contract, sysctl API, unused
in inet layer at this time (by inspection)).  sysctl is not
universally available, esp. on android-based systems.

Remove unused header <sys/sysctl.h>

---

src/test-apps/happy/bin/weave-register-service.py

-- In mac os, SysLoggerHandler should send to /var/run/syslog when using
standard python logging library.

Add python sys log address for mac on weave-register-service.py

---

src/adaptations/device-layer/FreeRTOS/SystemTimeSupport.cpp
src/adaptations/device-layer/nRF5/BLEManagerImpl.cpp
src/lwip/freertos/arch/sys_arch.h
src/lwip/freertos/sys_arch.c

* Correctly dispatch at compile time on the NRF_SDH_DISPATCH_MODEL
rather than on the enum that defines the model.  This change enables
the softdevice to actually use the right queue posting primitives.
* When NRF_DEBUG is enabled, softdevice will dispatch log statements
from interrupt context.  In order to support this, if appropriate,
log timestamping needs to be available; in turn, this implies that
TicksSinceBoot must be callable from interrupt context.  Since
FreeRTOS does not provide generalized facility to determine whether
a function is in an interrupt context, we make the symbol weak here,
and leave it to more specific adaptations to provide a more robust
implementation.

Fixes to the device layer/nRF implementation

---

src/adaptations/device-layer/FreeRTOS/SystemTimeSupport.cpp

Last minute changes to the code in PR436.  CI did not catch the
issue. This time around, I was able to build and verify the code works
as expected.

Typo: timeout vs. timeOut

---

src/adaptations/device-layer/ServiceProvisioningServer.cpp
src/lib/profiles/echo/Next/WeaveEchoClient.cpp
src/lib/profiles/echo/Next/WeaveEchoClient.h
src/lib/profiles/service-provisioning/ServiceProvisioning.h
src/lib/support/StatusReportStr.cpp
src/test-apps/TestStatusReportStr.cpp

Fixed spelling typo in the event and status code name: CommuncationError --> CommunicationError

Fixed spelling typo in CommunicationError

---

src/lib/core/WeaveBinding.cpp
src/lib/core/WeaveBinding.h

Various changes to Binding class in preparation for full support of WDM over connection-oriented transports.
- Revised the binding reset logic to preserve the configuration state of the binding while in the Failed state.  This allows code in the application’s BindingFailed handler to see the original binding configuration values, such as the peer’s node id.
- Modified Binding::IsAuthenticMessageFromPeer() to assert that an incoming message must be received over the same transport as the binding.  In the case of a connection, the message must have been received over the specific connection associated with the binding.
- Simplified the interface to the Binding::Configuration::ConfigureFromMessage() method and updated the logic to properly support messages received over a Weave connection.
- …

Binding enhancements for connection-oriented WDM

---

src/lib/profiles/security/WeaveTAKE.h

@robszewczyk I think you mentioned recently that this is a simple include oversight and should be removed?

Strip from TAKE protocol the dependency on third_party/micro-ecc

---

src/lib/profiles/vendor/nestlabs/device-description/NestProductIdentifiers.hpp
src/lib/profiles/vendor/nestlabs/dropcam-legacy-pairing/DropcamLegacyPairing.cpp
src/lib/profiles/vendor/nestlabs/dropcam-legacy-pairing/DropcamLegacyPairing.h
src/lib/profiles/vendor/nestlabs/thermostat/IfjStatusStr.cpp
src/lib/profiles/vendor/nestlabs/thermostat/NestThermostatWeaveConstants.h

This assumes the Apache 2.0 license for the as-opensourced modules found
in src/lib/profiles/vendor/nestlabs.

Assume Apache 2.0 license for vendor/nestlabs modules

---

src/lib/profiles/data-management/Current/SubscriptionClient.cpp

--When application trigger DiscardUpdate with WEAVE_NO_ERROR, pending
set state needs to be reset.

fix pending update state clean when discarding Update

---

src/lib/profiles/data-management/Current/NotificationEngine.cpp
src/lib/profiles/data-management/Current/NotificationEngine.h

--DataManagement Update Server needs to send notify to client when
subscription is there. In order to decrease the stack depth, add
ScheduleRun in NotificationEngine to achieve async notificaiton
engine run.

add ScheduleRun in NE

---

src/lib/profiles/data-management/Current/SubscriptionClient.cpp

--When application calls FlushUpdate, if no updated item is set,
mPendingSetState is kPendingSetEmpty, NoMorePendingEventCbHelper()
needs to be called, and notify application there is no more pending
updates.

NoMorePendingEventCbHelper needs to be called when flush empty updates

---

src/include/Makefile.am
src/lib/profiles/WeaveProfiles.am
src/lib/profiles/security/WeaveCertProvisioning.cpp
src/lib/profiles/security/WeaveCertProvisioning.h
src/lib/profiles/security/WeaveSecurity.h
src/lib/profiles/service-directory/ServiceDirectory.h
src/lib/support/StatusReportStr.cpp

-- Defined abstract interface object (WeaveNodeOpAuthDelegate)
to which platform specific actions are delegated during
Weave node operational authentication.
-- Defined abstract interface object (WeaveNodeManufAttestDelegate)
to which platform specific actions are delegated during
Weave node manufacturer attestation.
-- Defined and implemented certificate provisioning engine, used to
get new Weave operational device certificate from the CA service.

Implemented Certificate Provisioning Protocol Engine.

---

src/adaptations/device-layer/include/Weave/DeviceLayer/SoftwareUpdateManager.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericPlatformManagerImpl.ipp
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericSoftwareUpdateManagerImpl.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericSoftwareUpdateManagerImpl.ipp

The existing behavior reset the software timers based on connectivity
to the service: when connectivity to the service was lost, the exiting
timer was cancelled, and when connectivity to the service was
restored, the idle timer was restored.  The intended effect was to
avoid software update checks when they were doomed to fail (service
unreachable) while preventing "thundering herd" behavior on service
outages.  However, the actual most common behavior was to reset the
long-running timer on any flapping in Thread network connectivity.
The solution is to just use the software update timer policy,
oblivious to the service connectivity.  The new code fails eagerly in
`PrepareBinding` when there is no service connectivity, which
generates no useless network activity.  The platform events are …

Make the software update timer oblivious to service connectivity events

---

src/device-manager/python/openweave/WeaveBleUtility.py
src/device-manager/python/openweave/WeaveBluezMgr.py
src/device-manager/python/openweave/WeaveCoreBluetoothMgr.py

Bluez code contained a number of issues that were not caught earlier:
* `dbus.String` is essentially a string in Python3 but must be encoded
in Python 2 if we want to use it with any modules that expect a
string
* binascii.hexlify() returns a binary string. As such, it should
always be decoded
* Better handling bytearrays -- avoid unnecessary conversions to
string.

Fixup Python3 support in Device Manager /WoBLE code on Linux

---

src/lib/profiles/data-management/Current/TraitData.cpp
src/lib/profiles/data-management/Current/TraitData.h

--Add new MapPathToHandle API to handle path string, currently it does
not support dictionary.
--This API would be used in data management support for mobile client
side.
--In details, given a string positioned at the root tag of a WDM path,
the delimiter is /, read out the relevant tags and provide
the equivalent path handle.

Add MapPathToHandle API to handle path string

---

src/include/Makefile.am
src/lib/core/WeaveDMConfig.h
src/lib/profiles/WeaveProfiles.am
src/lib/profiles/data-management/Current/GenericTraitCatalogImpl.cpp
src/lib/profiles/data-management/Current/GenericTraitCatalogImpl.h
src/lib/profiles/data-management/Current/GenericTraitCatalogImpl.ipp

--Add GenericTraitCatalogImp support, which would be used in weave data
management support in mobile client side for several products.
--In details, mobile needs to update traits and refresh trait data from
device, and needs the trait catalogue to store traits, where we need
dynamic memory allocation for trait catalog item and resourceId support
, the existing SingleResourceTraitCatalog cannot meet the requirement,
we need this new GenericTraitCatalogImp.

Add GenericTraitCatalogImpl

---

src/lib/profiles/time/WeaveTime.h
src/lib/profiles/time/WeaveTimeClient.cpp

The `{ NULL } -> { }` is a bit of a RFC.  It resolves -Wmissing-field-initializers warnings, and I think it results in default-0 values in most C and C++ compilers.  RFC?

Weave time stray const

---

src/device-manager/python/build-openweave-wheel.py
src/device-manager/python/openweave/WeaveDeviceMgr.py

A few missing bits that made it past the previous changes:
* _BytesArrayToVoidPtr operates on `bytes` class rather than on `str`
class.  In Python 2, `bytes` is merely an alias for `str` so no
changes required, in Python3, `bytes` is the binary string returned by
various utilities such as `base64.b64decode()`
* Wheel packaging changed to reflect that the package is expected to
work on Python3.

Python3 compatibility for DeviceManager

---

src/device-manager/WeaveDeviceManager.cpp
src/device-manager/WeaveDeviceManager.h
src/device-manager/java/WeaveDeviceManager-JNI.cpp
src/device-manager/java/src/nl/Weave/DeviceManager/TestMain.java
src/device-manager/java/src/nl/Weave/DeviceManager/WeaveDeviceManager.java
src/device-manager/java/src/nl/Weave/DeviceManager/WirelessOperatingLocation.java
src/device-manager/java/src/nl/Weave/DeviceManager/WirelessRegulatoryConfig.java
src/device-manager/python/WeaveDeviceManager-ScriptBinding.cpp
src/device-manager/python/openweave/WeaveDeviceMgr.py
src/device-manager/python/weave-device-mgr.py
src/include/Makefile.am
src/lib/profiles/WeaveProfiles.am
src/lib/profiles/network-provisioning/NetworkProvisioning.cpp
src/lib/profiles/network-provisioning/NetworkProvisioning.h
src/lib/profiles/network-provisioning/WirelessRegConfig.cpp
src/lib/profiles/network-provisioning/WirelessRegConfig.h
src/lib/support/StatusReportStr.cpp
src/test-apps/MockNPServer.cpp
src/test-apps/MockNPServer.h
src/test-apps/TestWeaveDeviceMangerJNI
src/test-apps/happy/lib/WeaveDeviceManager.py

This change implements the feature described in https://github.com/openweave/openweave-core/issues/399.
- Added three new message types to the Network Provisioning profile:
GetWirelessRegulatoryConfig, GetWirelessRegulatoryConfigComplete and SetWirelessRegulatoryConfig.
- Extended the NetworkProvisioningServer and NetworkProvisioningDelegate classes to support the new provisioning protocol.
- Created WirelessRegConfig class and associated types to represent wireless regulatory config in memory and provide functions for encoding/decoding to Weave TLV.
- Added APIs to C++ WeaveDeviceManager class for getting and setting wireless regulatory configuration information. Extended the Java and Python (but not Objective-C++) wrappers for the Device Manager to support the APIs.
- Added support for …

Network Provisioning: Support for wireless regulatory provisioning

---

build/efr32/efr32-app.mk
build/efr32/efr32-freertos.mk
build/nrf5/nrf5-app.mk

-- Allow clean target to be extended.
-- Adjust logging output from efr32-freertos.mk to match other makefiles.
-- Use ccache when compiling FreeRTOS.
-- Fixed help text in efr32-freertos.mk.

Minor cleanups for example app makefiles

---

src/lib/profiles/data-management/Current/MessageDef.h
src/lib/profiles/data-management/Current/SubscriptionEngine.cpp
src/lib/profiles/data-management/Current/SubscriptionEngine.h
src/lib/profiles/data-management/Current/TraitData.h

-- Remove unsupported kEventChangeBegin and kEventChangeEnd
-- Add kEventUpdateProcessingComplete, trigger it when updating trait version.
-- Update status report using kStatus_BadRequest when update request is malformed.
-- Add kStatus_InvalidValueInUpdate to represent data element value error in wdm
profie.
-- When processing update request, we need to skip this DE when DE generates
WEAVE_ERROR_WRONG_TLV_TYPE and WEAVE_ERROR_TLV_TAG_NOT_FOUND.
-- Rename BuildStatusDataHandleElement to UpdateStatusDataHandleElement
-- Add InitializeStatusDataHandleList to initialize StatusDataHandleList
with defaut incorrect state, whenenever the data element in list has
been processed successfully, update StatusDataHandleList with sucess
status. Once it hit fatal error, we end up the conditional and …

several changes on update server

---

src/lib/core/WeaveError.cpp
src/lib/core/WeaveError.h
src/lib/core/WeaveFabricState.cpp
src/lib/core/WeaveFabricState.h
src/lib/core/WeaveSecurityMgr.cpp
src/lib/profiles/security/WeaveSecurity.h
src/test-apps/weave-ping.cpp

- Added methods to WeaveFabricState to suspend and restore an active Weave security session in a serialized form.  This feature can be used by devices that do not retain RAM when sleeping to avoid the need to re-establish sessions on wake.
- Added option to weave-ping tool to exercise the session suspend/restore APIs.

Support for suspending and restoring Weave security sessions

---

src/adaptations/device-layer/NetworkTelemetryManager.cpp
src/adaptations/device-layer/include/Weave/DeviceLayer/NetworkTelemetryManager.h
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericPlatformManagerImpl.ipp

-- This enables Network Telemetry Manager to upload Thread/Wifi/Tunnel
telemetry data periodically.

Initialize Network Telemetry Manager during weave stack initialization

---

build/config/android/WeaveProjectConfig.h
build/config/ios/WeaveProjectConfig.h
build/config/standalone/WeaveProjectConfig.h
src/device-manager/WeaveDeviceManager.cpp
src/device-manager/WeaveDeviceManager.h
src/device-manager/cocoa/NLWeaveStack.mm
src/device-manager/java/WeaveDeviceManager-JNI.cpp
src/device-manager/python/WeaveDeviceManager-ScriptBinding.cpp
src/device-manager/python/weave-device-mgr.py
src/lib/core/WeaveConfig.h
src/lib/core/WeaveMessageLayer.cpp

- Assign a random Weave node id to the local Weave stack when the WeaveDeviceManager is used on Android, iOS and from within Python.  This ensures that devices will treat separate WeaveDeviceManager instances running in different processes on the same host as distinct Weave nodes.
- Enabled use of an ephemeral UDP port for outgoing communication from the WeaveDeviceManager on the Android, iOS and Python.
- Added a build feature that enables listening on the Weave UDP port only when the Device Manager is attempting to identify or rendezvous with a device.  This reduces competition for the Weave port when the WeaveDeviceManager is used by multiple processes on the same host. This feature is enabled by default on Android, iOS and within Python.
- Minor adjustments to logging in …

Improved multi-process support in WeaveDeviceManager

---

src/tools/weave/Cmd_GenCACert.cpp
src/tools/weave/KeyUtils.cpp
src/tools/weave/weave-tool.h

to be a public key (PEM or DER). Currently the tool requires a private key,
which is not available in some scenarios.

Modify weave tool (gen-ca-cert command) to allow the -key argument

---

src/lib/core/WeaveConfig.h
src/lib/profiles/service-directory/ServiceDirectory.cpp
src/lib/profiles/service-directory/ServiceDirectory.h

-Add WEAVE_CONFIG_PERSIST_SERVICE_DIRECTORY for enabling and disabling this feature
-Save the byte stream received from directory server to persistent storage if ‘ServiceDirectory Redirect’ is not issued.
-Clear persisted storage whenever cache is cleared.

Persistent service directory

---

build/nrf5/nrf5-openthread.mk

This will pass the FreeRTOS includes used by the application to OpenThread so a common version will be used, similar to the NDK include paths.

[freertos] Pass freertos includes to openthread.

---

src/adaptations/device-layer/ServiceProvisioningServer.cpp

printf format %*s is not limiting the string size, here we should use
%.*s to limit the output length.
Change-Id: Iea875e06e0df786b9a0a7f03f1a7bcaba2a1b9b4

Fix printf buffer overflow

---

src/lib/profiles/data-management/Current/ResourceIdentifier.cpp
src/test-apps/TestResourceIdentifier.cpp

ResourceIdentifier parsing code overly optimistically assumed a fixed
length of the actual ResourceID.  The parsing code only checked that
the buffer length was larger than the resource prefix, and after that,
it assumed the actual resource ID was a fixed string of 16 hexadecimal
digits. This pull request addresses that shortcoming.
The test code was incorrect as well, passing the size of the pointer
into the `FromString` methods as opposed to size of the buffer.  This
led to the tests succeeding on platforms with 64 bit pointers (only in
conjunction with the bug above) and failing on platforms with 32 bit
pointers.

Address issues in ResourceIdentifier parsing and tests.

---

src/test-apps/mock-weave-bg.cpp

Needed to update that as in some test cases Topaz2 device
may have limited capabilities.

Updated WeaveProductId Used In the mock-weave-bg.

---

src/system/SystemTimer.cpp

Calling `nl::Weave::System::Timer::Start` does not wake the Weave
thread. This is arguably an understood limitation stemming from Weave
code being geared towards a single-threaded execution.  However, on a
number of platforms -- such as Java -- we admit to having pieces of
the Weave stack run within different threads but enclosed within the
correct lock around the Weave stack.  This results in issues where the
Java caller schedules a timer: the main Weave thread may be sleeping
in the event loop and does not adjust the wake time in response to the
new timer being scheduled.
The construction proposed herein parallels the semantics
`nl::Weave::System::Timer::Start` offers on LwIP systems and parallels
the semantics offered by `ScheduleWork`.
On systems where POSIX locking is already …

On sockets platforms, starting a timer should wake up layer's event loop

---

Makefile-Android

-- Internal android weave daily build fails in
src/lib/../../src/device-manager/WeaveDataManagementClient.cpp:39:18:
fatal error: string: No such file or directory
#include <string>
-- At default, it uses system, but it don't have c++ string,
/usr/local/android/android-ndk-r14/system/include.
-- if using libc++, it has
/usr/local/android/android-ndk-r14/sources/cxx-stl/llvm-libc++/include/string.
-- Therefore, use Android NDK C++ runtime to build against libc++
-- checking latest android ndk, the same applies.

Use libc++ as default Android STL when make Makefile-Android

---

src/lib/profiles/device-control/DeviceControl.cpp

If any failsafe is active when reset-config is called, it should not be
reset or cancelled. The same applies for HandleResetConfigConnectionClose.
This change also removes error handling that was checking for
WEAVE_ERROR_NOT_IMPLEMENTED, which was not quite correct.

Remove failsafe reset code from HandleResetConfig

---

src/lib/profiles/data-management/Current/CommandSender.cpp
src/lib/profiles/data-management/Current/CommandSender.h

- fix uninitialized value in OnSendError
- rename error to sendError to be more clear
- remove meaningless const qualifier from SynchronizedTraitState::HasDataCaughtUp(void)

CommandSender: fix compiler warnings

---

Makefile-iOS

Autodection for python builds is triggered on availability of the wheel on the build platform.  Disable installable python package on iOS explicitly in the `Makefile-iOS`

Do not build python wheel packages for iOS.

---

src/adaptations/device-layer/include/Weave/DeviceLayer/OpenThread/GenericThreadStackManagerImpl_OpenThread.ipp

-- In the Generic Thread Stack Manager Impl using OpenThread,
thread stack was not unlocked before returning from an error encountered
while gathering telemetry related information using openthread APIs.

Fix a bug in thread network telemetry.

---

src/test-apps/MockWdmSubscriptionResponder.cpp

The test code for managing the binding in the
MockWdmSubscriptionResponder.  The logic bug was present for some
time, but skipped past unnoticed.  The core issue is as follows: we
grab a reference to `gBinding` when the SubscriptionEngine generates a
`kEvent_OnSubscriptionEstablished` (line 654 above the patch); that
reference is logically bound to the publisher and no to the client
(and to the mutual countersubscription).  As a result, the reference
to the binding object will be released as a result of
SubscriptionEngine generating a `kEvent_OnSubscriptionTerminated`; in
this code this takes place as a result of calling
`HandlePublisherRelease()` in line 802 below.  The error handling
takes place via checking for errors in the `exit:` label and takes a
form of `EndSubscription()`. As a …

Fix test code for MockWdmSubscriptionResponder

---

src/lib/profiles/security/WeaveSig.cpp
src/lib/profiles/security/WeaveSig.h

In the variant of the function where output is EncodedECDSASignature
structure, the R and S values of the signature should be copied
and not just referenced.

Fixed Function Implementation that Converts DER to Weave Signature.

---

src/adaptations/device-layer/LwIP/WarmSupport.cpp
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/GenericConnectivityManagerImpl_Thread.ipp
src/warm/WarmCore.cpp

This PR adds related openthread api call to WarmSupport in LwIP.
- When add or removing thread addresses, will also add weave thread subnet mesh prefix to thread stack.
- Add fabric prefix to thread border router.

[Thread] Support Weave thread border routing

---

configure.ac

Because NL_WITH_OPTIONAL_INTERNAL_PACKAGE may use pkg-config to find
external BlueZ library, pkg-config must be checked before it.
Change-Id: If48d395bf6da2db03c608efe7603ee37273c40a8

Configure: check pkg-config before BlueZ

---

src/device-manager/python/WeaveDeviceManager-ScriptBinding.cpp
src/device-manager/python/openweave/WeaveStack.py
src/lib/support/logging/WeaveLogging.cpp
src/lib/support/logging/WeaveLogging.h
src/test-apps/happy/lib/WeaveDeviceManager.py

- **Reworked the way developer logging happens when using the openweave wrappers for python.** With this change, all WeaveLog...() calls in C++ code result in a callback to a logging function in python.  The default implementation of this function directs log messages to a standard python logger object associated with the python WeaveStack object.  By default, the python logger is configured to output messages to stdout, in a format identical to that used by the C++ code.  However, developers are free to reconfigure the logger object, or replace it altogether, giving them complete control over the handling of C++ generated logs in python applications.
- **Added support for dynamic logging behavior.**  Modified the standard implementation of nl::Weave::Logging::Log() so that the default …

Improved logging in python

---

src/device-manager/python/openweave/WeaveStack.py

By default, include the openweave module prefix in the log message strings delivered to the python logger object.  This ensures the information gets logged when using a default log formatter.  The behavior can be overridden in situations where a logger wants more control of the final message format.

Automatically add module prefix to python openweave logs

---

src/lib/support/logging/WeaveLogging.cpp

-- use ap instead of v in DefaultLogMessage

Fix typo in DefaultLogMessage

---

src/device-manager/python/WeaveDeviceManager-ScriptBinding.cpp
src/lib/support/logging/WeaveLogging.cpp

* Minor typo in Android logging code.
* Fix conditional compilation in Python bindings -- when no logging is
enabled at configuration time, logging functions are not present in
the library, and thus should not be used in Python module

Minor fixes to the revised logging code

---

src/wrappers/jni/security-support/native/WeaveSecuritySupport.cpp

-- Without this change, the linking of the WeaveSecuritySupport library fails at
runtime for android app support.

Fix linking issue for WeaveSecuritySupport target in Android app

---

src/lib/core/WeaveFabricState.cpp
src/lib/core/WeaveFabricState.h
src/lib/profiles/fabric-provisioning/FabricProvisioning.cpp
src/lib/profiles/fabric-provisioning/FabricProvisioning.h
src/lib/profiles/network-provisioning/NetworkProvisioning.cpp
src/lib/profiles/network-provisioning/NetworkProvisioning.h

These relaxed access controls would allow a mobile client device that
is connected over PASE during first-device pairing to access device
credentials only over that same session, and cache them for
assisting other devices during subsequent pairing attempts.

Access Control relaxation for fetching device credentials over a PASE session

---

src/lib/support/crypto/RSA.cpp

clang complained about the implicit conversion - this more clearly
shows what is being done to the pointer.
Bug: 155214583
Change-Id: I90f01a46c4f0eb08388a0c6dcf9c4dbdd5a73d75

Specifically cast certDER to void*.

---

src/lib/profiles/data-management/Current/CommandSender.cpp

Fixes a bug in CommandSender where providing SendCommand with a binding
argument doesn't override the default binding.

Fix CommandSender::SendCommand with binding override

---

src/lib/core/WeaveFabricState.cpp

Should use AnonymousTag to read out shared session endnode.

Fix TLVreader context tag err

---

build/nrf5/nrf5-openthread.mk
src/adaptations/device-layer/include/Weave/DeviceLayer/OpenThread/GenericThreadStackManagerImpl_OpenThread.ipp

To use new OpenThread, set OPENTHREAD_API_VERSION_MINIMAL to a
non-zero value which indicates the minimal OpenThread API version
required for the project.
This commit keeps OPENTHREAD_API_VERSION_MINIMAL to 0 by default because
other openweave projects is still using an old OpenThread.

Support new OpenThread with OPENTHREAD_API_VERSION

---

build/esp32/components/openweave/component.mk
src/adaptations/device-layer/ESP32/AESBlockCipher.cpp
src/adaptations/device-layer/ESP32/ConnectivityManagerImpl.cpp
src/inet/DNSResolver.cpp

This PR cherry picks [`f70c83b`](https://github.com/openweave/openweave-core/commit/f70c83b82b6202e36b5a782abe524edd4a997480) to master.
After patched ESP-IDF 3.2, these updates is required by ESP-IDF 3.3
- Update `component.mk` to build `libopenweave.a`
ESP-IDF 3.3 assumed that `lib(componentname).a` is built
- dns_getserver now returns `const ip_addr_t*`
Testing this PR requires https://github.com/openweave/openweave-esp32-demo/pull/14 and its lwip submodule should be checked out to https://github.com/openweave/openweave-esp32-lwip/pull/2
Tested features:

[ESP32] Add ESP-IDF 3.3 support

---

src/inet/TunEndPoint.cpp

TunEndPoint::LwIPPostToInetEventQ() does not currently account for WEAVE_TRAILER_RESERVE_SIZE when it allocates a new PacketBuffer for a packet received from the LwIP layer. This space is needed for encryption information.

Add WEAVE_TRAILER_RESERVE_SIZE to Tunnel pbuf allocation from LwIP

---

src/lib/profiles/data-management/Current/MessageDef.cpp
src/lib/profiles/data-management/Current/SubscriptionClient.cpp
src/test-apps/happy/lib/WeaveDeviceManager.py

-- There exists VersionList::Builder::AddNull API which has been used
for null version set when trait version cannot be obtained in server
side in some situations, for example, trait access denied or profile id
or instance id is not correct and so on. In correspondence, we need to
do the null version correctly in VersionList::Parser::GetVersion(current
implementation does not check this null version case), and set apVersion
as 0 which means invalid version, and return WEAVE_NO_ERROR, otherwise,
SubscriptionClient would fails to process OnUpdateResponse and go to exit when
triggering versionList.GetVersion in L2572, and further set the internal
error for all paths in current flush operation even though other paths
have been updated correctly.
-- Add test case to validate this case.

Fix null version case for VersionList::Parser::GetVersion

---

src/device-manager/python/openweave/WeaveCoreBluetoothMgr.py

-- In mac os macosx_10_15, we find the corebluetooth path has become
/System/Library/Frameworks/CoreBluetooth.framework. Update it in
WeaveCoreBluetoothMgr

Fix corebluetooth framework path

---

src/lib/profiles/data-management/Current/SubscriptionEngine.cpp

-- When handling unconditional update loop, we can skip the successful
updated data elements marked by conditional update loop.

Skip successful updated data elements

---

src/lib/profiles/data-management/Current/LoggingManagement.cpp

Print importance level and dropped event count as a parsable format

Add Log lines to monitor dropped events, by importance level

---

src/lib/core/WeaveFabricState.cpp
src/lib/core/WeaveFabricState.h
src/lib/core/WeaveSecurityMgr.cpp
src/lib/core/WeaveTunnelConfig.h
src/lib/profiles/security/WeaveSecurity.h
src/lib/profiles/weave-tunneling/WeaveTunnelAgent.cpp
src/lib/profiles/weave-tunneling/WeaveTunnelAgent.h
src/lib/profiles/weave-tunneling/WeaveTunnelConnectionMgr.cpp
src/lib/profiles/weave-tunneling/WeaveTunnelConnectionMgr.h
src/test-apps/Makefile.am
src/test-apps/TestWeaveTunnel.h
src/test-apps/TestWeaveTunnelCASEPersistClient.cpp
src/test-apps/TestWeaveTunnelCASEPersistServer.cpp

Changes to support persistence of CASE session for the Tunnel.
During connection establishment by the Tunnel Agent, if a persisted
session key exists, the TunnelAgent first establishes an unsecured 
WeaveConnection and then calls back into the application to load the
session key for the created Weave connection object.
When the connection goes down, and before the FabricState removes the
SessionKey, the application is called back to suspend the session into
a serialized form to be persisted.
At time of suspension, resumption message Ids(for both the next message
id to send, as well as the last received message id from peer) are
calculated using a fixed offset and included within the session key.
When the session resumes, it would start off communication using the
resumption message ids. …

Tunnel CASE Session persistence support.

---

src/lib/core/WeaveFabricState.cpp

The ResumptionMsgId valid field needs to be serialized so that during restoration it can be retrieved from persistent storage. This was not getting stored for the Shared CASE session with WCRS.

Fix for resumption message id valid tag.

---

src/lib/profiles/weave-tunneling/WeaveTunnelAgent.cpp
src/lib/profiles/weave-tunneling/WeaveTunnelAgent.h
src/lib/profiles/weave-tunneling/WeaveTunnelConnectionMgr.cpp
src/lib/profiles/weave-tunneling/WeaveTunnelConnectionMgr.h

Needed for getting information about PeerAddress, PeerPort of TunnelConnection as well as suspension of TunnelConnection CASE session persistence during shutdown.

Surface a getter function for retrieving the WeaveConnection object for the Tunnel connection

---

src/device-manager/cocoa/NLLogging.h
src/device-manager/cocoa/NLWeaveLogWriter.h
src/device-manager/cocoa/NLWeaveLogging.h
src/device-manager/cocoa/NLWeaveLogging.mm

Allow external clients using the Objective-C OpenWeave framework to register a "Weave Log Writer" to pass Weave logs to a custom logging component.
Changes:
- Adds `NLWeaveLogging` to manage processing Weave logs.
- Adds `NLWeaveLogWriter` protocol for external clients to implement and set with `+[NLWeaveLogging setSharedLogWriter:]`.
- Updates `WDM_LOG` macros and `nl::Weave::Logging::Log` function to pass logs to the new `NLWeaveLogging` manager.
- Adds `NLOSLogStore` to act as a map from `NLLogModule` values to individual `os_log_t` components.
TESTED=Called `+[NLWeaveLogging setSharedLogWriter:]` and confirmed that the `NLWeaveLogWriter` received Weave logs as expected. Also viewed app logs in the Console app and confirmed the OSLog components were correctly configured.

[Logging][Obj-C] Add external log writer interface.

---

src/inet/TCPEndPoint.cpp
src/inet/TCPEndPoint.h

* Weave, when using an lwIP networking interface, employs
the raw lwIP callback-based scheme to handle TCP sends.
In order to avoid multiple copies of packet buffers on
small devices, the TCP sends are done in-place over the
incoming packet buffers. Packet buffers must be retained
in full until acknowledgement has been received by lwIP.
* The existing logic had a corner case where if there was
more data queued than the local TCP send window, the
accounting of buffers and lengths to retain the un-acked
buffers could get out of balance, leading to an eventual
crash. This was root caused to an invalid assumption that
the packet buffer chain did not need traversal for offset
readjustment (which is true in most cases, only by
coincidence).
* This change removes separate accounting of the …

Fix Weave TCPEndPoint crash in some lwIP cases

---

src/lib/profiles/data-management/Current/LoggingManagement.cpp

There are several reports that urgent events such are doorbell events failed to make to cloud. It's possible that urgent events failed to schedule flush and later get dropped silently due to event buffer overflow. Add more logs to indicate the status of scheudling flush for urgent events to see if there's any correaltion that need to be wary about.
In addition, NCCM people reported that they only called nl::Logevent once but multiple events are logged at the same timestamp. Currently WeaveLogDetail is disabled on user build and we don't have any logs regarding the event logging on weave side. Increasing the log level of 'logevent' to WeaveLogProgess. This should be ok as it's still guarded by WEAVE_CONFIG_EVENT_LOGGING_VERBOSE_DEBUG_LOGS.
This change will
1) Add debug logs for scheduling …

Add nl::Logevent debug logs

---

src/lib/profiles/data-management/Current/LoggingManagement.cpp
src/lib/profiles/data-management/Current/NotificationEngine.cpp

In this change we 
1) specify the event id range of dropped events, 
2) Log profileId and print out the message when logEvent failed and returned 0.
3) Log range of event_id fetched and being flushed

Add more logs to help debug event missing issue

---

src/test-apps/Makefile.am

Coverage targets that included test_weave_pairing_01.py were failing on some builds, this change fixes the header location.

Add a path fixup for DeviceManager headers

---

src/lib/core/WeaveConfig.h
src/lib/profiles/data-management/Current/NotificationEngine.cpp

Useful in some scenarios where events need to be sent out as soon as possible without having to wait for trait data changes.

Add option to pack events from eventlist in NotifyRequest before trait-data properties from datalist

---

src/lib/core/WeaveConfig.h
src/lib/profiles/data-management/Current/NotificationEngine.cpp
src/lib/profiles/data-management/Current/SubscriptionClient.cpp
src/lib/profiles/data-management/Current/SubscriptionClient.h
src/lib/profiles/data-management/Current/SubscriptionEngine.cpp
src/lib/profiles/data-management/Current/SubscriptionEngine.h
src/lib/profiles/data-management/Current/SubscriptionHandler.cpp
src/lib/profiles/data-management/Current/SubscriptionHandler.h

This commit enables a set of APIs to persist and restore the
subscription state.  Such functionality may be used when the
Weave process needs to shutdown and restart in an orderly fashion
while preserving the illusion that the subscription remains
unchanged.  In order to successfully accomplish this task, the
commit introduces the functionality to:
* serialize SubscriptionClient and SubscriptionHandler data.  
* load SubscriptionClient and SubscriptionHandler from
serialized data and integrate it into the subscription engine
mechanisms.
* find established subscription handlers and clients from the SubscriptionEngine

Subscription state persistence

---

src/ble/BLEEndPoint.cpp
src/device-manager/WeaveDeviceManager.h
src/device-manager/cocoa/NLWeaveBleDelegate.mm
src/device-manager/cocoa/NLWeaveDeviceManager.mm

In openweave, when application call device manager Close, which would send unsubscribe request to peripheral, and start the unsubscribe timer, after it receive unsubscribe confirm or timeout happens, openweave would close ble endpoint's connection.
App don't know when the ble connection goes away when using above async Close and use delay/retry to alleviate this issue, but failure may still happen, so we force close ble endpoint no matter whether we receive unsubscribe confirm or not.
we see iOS app forces ble connection close before weave close  so that ios app would not send woble unsubscribe request to close woble connection in device.In order to fix this issue, we move ble disconnection after woble shutdown/close so that unsubcribe can be sent out and further disable autoclose when …

Improve woble connection close

---

src/inet/TunEndPoint.cpp

The compile is failing with -Werror enabled. In this particular case, a
call to strncpy can fail to null-terminate tunIntfName if ifr.ifr_name
is maxed out on its number of characters.
The compiler pretty-much expects the user to explicitly set the null
terminator at the end of the copied-to array in order to address the
warning, so that's what we do here.
Relevant compiler output (though it's a little cryptic):
```
src/inet/TunEndPoint.cpp:697:16: error:
'char* strncpy(char*, const char*, size_t)' output may be truncated
copying 15 bytes from a string of length 15
[-Werror=stringop-truncation]
697 |         strncpy(tunIntfName, ifr.ifr_name, sizeof(tunIntfName) - 1);
|         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Address truncation warning in gcc 8+

---

src/lib/core/WeaveConnection.cpp

Set DestNodeId flag for repaired WeaveConnection if PeerAddress is not IPv6ULA.
Necessary for the Tunnel TCP connection over IPv4.

Set DestNodeId flag for repaired WeaveConnection

---

src/lib/profiles/weave-tunneling/WeaveTunnelAgent.cpp
src/lib/profiles/weave-tunneling/WeaveTunnelAgent.h
src/lib/profiles/weave-tunneling/WeaveTunnelConnectionMgr.cpp
src/lib/profiles/weave-tunneling/WeaveTunnelConnectionMgr.h
src/lib/profiles/weave-tunneling/WeaveTunnelControl.cpp

This provides an additional level of granularity in application event notification during Tunnel bringup

Notify application when Tunnel TCP connection is set up.

---

src/device-manager/python/build-openweave-wheel.py

We've noticed that Openweave Python packages on PyPI are only uploaded
for specific Python versions. This was a problem when we switched from
Python 3.7 to Python 3.8, and it was finally solved by uploading a new
Python package to PyPI. But now we've switched to Python 3.9 and the
problem surfaced again... so it's high time we find a better solution.
Since Openweave Python package includes, and wraps around, a binary
shared object, it is not a "pure" package.  However, in that case,
Python's "wheel" packer assumes the package uses Python ABI (e.g. it
builds a Python module as a shared object), and tags it with the version
of ABI and the interpreter. Openweave does not use Python ABI, so this
is an unnecessary constraint. This PR removes it.

Openweave Python packages should not depend on Python ABI version

---

src/inet/TCPEndPoint.cpp
src/lib/profiles/weave-tunneling/WeaveTunnelConnectionMgr.cpp

Also, remove redundant call to ServiceMgr->cancel() when closing a repaired connection.

Retain TCPEndPoint upon TCP repair

---

src/lib/profiles/data-management/Current/SubscriptionHandler.cpp

If subscription is not persisted, publisher sends trait data to client
after client sends trait version list to publisher during subscription.
If subscription is persisted, we load trait instance from persisted data.
Currently, we set all trait instance to dirty when we load  the
trait instances. This would sometimes result in sending empty traits to
client. This PR stops marking trait instance as dirty during loading
subscription.

Do not set trait instance to dirty after loading persisted subscription

---

src/lib/profiles/data-management/Current/SubscriptionClient.cpp
src/lib/profiles/data-management/Current/SubscriptionHandler.cpp

SubscriptionClient is written in a way that it's not released upon abort. When peer send
a "cancel subscription" request, SubscriptionClient is reset to initiated state and
is going to be reused by the next subscription attempt. However, SubscriptionClient
only sets the protocol callback on its binding upon init(), which doesn't happen
when the same subscriptionClient is reused for the second (and new) subscription
attempt.
In recent tests, we found that some application resets binding during AbortSubscription.
In some corner cases, when subscriptionClient is reused for second subscription, 
protocol callback is not set for its binding.  We should double check binding has 
valid protocol callback when InitiateSubscription() happens. This PR is also a temporary 
fix to unblock …

Make sure protocol callback is set on the binding object in SubscriptionClient

---

src/lib/profiles/data-management/Current/SubscriptionClient.cpp

Make double sure the protocol callback is set on the binding object.

Move SetProtocolLayerCallback from InitiateSubscription to _prepareBinding

---

src/lib/profiles/data-management/Current/SubscriptionHandler.cpp
src/lib/profiles/data-management/Current/SubscriptionHandler.h

mDeliveredEvent is set to 0 during initialization, and updated after ack from client is recieved. when WEAVE_CONFIG_PERSIST_SUBSCRIPTION_STATE is enabled, prefer mDeliveredEvents over event ids sent from client to update mSelfVendedEvents. This would further reduce the traffic during subscription establishment if client sends old event id.

Prefer using mDeliveredEvents to update mSelfVendedEvents

---

src/device-manager/cocoa/NLWeaveStack.mm

Prevent occasional crash during NLWeaveStack shutdown.
If shutdown fails, NLWeaveStack needs to nil-out the stored callback block.
If for some reason the callback block is called multiple times, NLGWeaveDeviceManager should make sure the calls to dispatch_group are balanced.

Prevent occasional crash during NLWeaveStack shutdown.

---

src/device-manager/cocoa/Makefile.am
src/device-manager/cocoa/NLWeaveDeviceManagerTypes.h
src/device-manager/cocoa/NLWeaveLogging.h

- Add NLWeaveLogging.h to Makefile.am so it's included in the exported headers.
- Fix incorrect #pragma statements in NLWeaveLogging.h
- Add missing #include to NLWeaveDeviceManagerTypes.h

Fix broken iOS build.

---

build/config/android/WeaveProjectConfig.h
build/config/ios/WeaveProjectConfig.h

Nest D3 devices require a specific src and dest UDP port. Enabling this feature prevents D3 devices from being used in assisted pairing.

Disable the ephemeral UDP port feature.

---

src/lib/core/WeaveConnection.cpp

https://crash.corp.google.com/browse?q=stable_signature%3D%27nl%3A%3AWeave%3A%3AWeaveConnection%3A%3ADoClose-24bb06ea%27

Add NULL-check for `MessageLayer->FabricState` on connection close.

---

src/lib/core/WeaveTLVReader.cpp
src/test-apps/TestTLV.cpp

1. For some reason the Get(float&) signature was declared in the .h file
but was never defined. Define it as well. Disallow reading a 64-bit
floating point number to float, to avoid silent truncation / loss of
precision.
2. It is undefined behaviour to use unions for type-punning in C++. Use
raw memcpy calls instead, which is defined by the C++ standard
(std::bit_cast is not available).
Compilers will generally be able to optimize this memcpy away, unless
a freestanding implementation (with possibly non-standard memcpy) is
used.
This is a backport from an analogous commit to CHIP:
https://github.com/project-chip/connectedhomeip/pull/8531

TLV reader: Improve floating-point support

---

src/lib/profiles/security/WeaveKeyExportClient.cpp

The problem that development apps that don't set DEBUG flag
cannot accept CRK export from development device.

Allow CRK Export from Development Devices for Apps with non-DEBUG Config.

---

src/lib/core/WeaveMessageLayer.cpp

Limit UDP broadcast to interfaces that are up and have broadcast addresses. SendMsg fails with `EINVAL` on iOS if this criteria is not met.
Upstream commit for cl/390147653.

Filter network interfaces on UDP broadcast.

---

src/lib/profiles/data-management/Current/UpdateEncoder.h

GCC's class-memaccess warning reports cases where functions like memset,
memcpy, etc. are used on non-trivial types.  This change replaces a
memset(this, 0, sizeof(*this)) in the DataElementDataContext struct with
explicit zero-initialization of each member, since
DataElementDataContext is a non-trivial type (member mTraitPath has a
user-defined default constructor).

Fix class-memaccess warning from GCC 9

---

src/device-manager/WeaveDataManagementClient.cpp
src/device-manager/WeaveDataManagementClient.h
src/inet/IPAddress.cpp
src/inet/IPAddress.h
src/inet/IPPrefix.cpp
src/inet/IPPrefix.h
src/lib/core/HostPortList.cpp
src/lib/core/HostPortList.h
src/lib/profiles/data-management/Current/Command.h
src/lib/profiles/data-management/Current/CommandSender.cpp
src/lib/profiles/data-management/Current/LoggingManagement.cpp
src/lib/profiles/data-management/Current/UpdateClient.h
src/lib/profiles/data-management/Current/UpdateEncoder.h
src/lib/support/crypto/CTRMode.cpp
src/lib/support/crypto/DRBG.cpp
src/test-apps/MockSourceTraits.h
src/test-apps/MockWdmSubscriptionResponder.cpp
src/test-apps/TestSystemObject.cpp
src/test-apps/TestWdmUpdateServer.cpp
src/test-apps/TestWeaveTunnelCASEPersistClient.cpp

* Fix class-memaccess warning in src/lib/support/crypto/CTRMode.cpp
and in src/lib/support/crypto/DBRG.cpp by implementing a more robust
constructor
* Remove unused local variables in
src/device-manager/WeaveDataManagementClient.cpp
* Remove trivial implementations of `operator=` in
src/inet/IPAddress.{h,cpp} and in src/inet/IPPrefix.{h,cpp} s.t. any
classes containing members of these types remain trivially copyable.
* Fix several warnings about comparisons between signed and unsigned integers.
* Remove the duplicated enum within the class completely
mirrored/shadowed the enum within the namespace
(DataManagement_Current::Command::CommandFlags)
* Replace memset-based initialization with the 0-initialization constructor
* Replace the no-arg constuctor for HostPortList with the default one …

Fix several warnings issued by the more modern compilers

---

src/lib/core/ExchangeContext.cpp
src/lib/core/WeaveBinding.cpp
src/lib/core/WeaveBinding.h
src/lib/core/WeaveConfig.h
src/lib/core/WeaveConnection.cpp
src/lib/core/WeaveExchangeMgr.cpp
src/lib/core/WeaveExchangeMgr.h
src/lib/core/WeaveMessageLayer.cpp
src/lib/core/WeaveMessageLayer.h
src/lib/profiles/weave-tunneling/WeaveTunnelAgent.cpp
src/lib/profiles/weave-tunneling/WeaveTunnelAgent.h
src/test-apps/TestWeaveTunnel.h
src/test-apps/TestWeaveTunnelBR.cpp

This feature allows an application to formulate an Exchange for
capturing Weave messages by setting a WeaveBindiing flag before vending
the ExchangeContext. For tunneled messages, they are directed towards a
'capture subnet' as a means of tagging the messages for capturing, as
they traverse the underlying network stack and get encapsulated within
an [IPv6|UDP] packet. The capture subnet is then reinstated back to the
original subnet before the packet is captured and delivered up to
the application.
* Expose WeaveBinding setting API.
* Percolate setting via message flags from WeaveExchange layer to
WeaveMessageLayer.
* Encode reserved capture subnet for Tunneled packets to Phoenix
* Reinstate Phoenix address and tag tunneled packet for capture.
* Add functional test case for capturing a …

Weave Message Capture logic.

---

src/lib/core/WeaveTLVDebug.cpp
src/test-apps/TestWeaveTunnelBR.cpp
src/tools/weave/Cmd_PrintAccessToken.cpp
src/tools/weave/Cmd_PrintServiceConfig.cpp
src/tools/weave/Cmd_PrintTLV.cpp
src/tools/weave/Makefile.am
src/tools/weave/weave-tool.cpp
src/tools/weave/weave-tool.h

* add a command to print out the contents of the access token
* add a command to print out the contents of the service config object
* add the ability to specify the implicit profile ID to the print-tlv command
* change the printing of binary string dump to dump the contents rather than the pointer value

Weave tool improvements

---

src/lib/support/StatusReportStr.cpp

The optimization slightly increases the text size, and significantly
decreases the size of readonly data.  On a typical embedded platform,
we expect a net flash savings of over 2.5 kbytes.

Split status report strings to save flash

---

Makefile-iOS

Weave builds for iOS have been arguably somewhat incorrect.  The
Makefile-iOS used to generate a single Weave.framework for both
iPhoneOS and for iPhoneSimulator.  This became problematic in XCode
13, when the simulator architectures (x86_64, i386) were no longer
supported in the iPhoneOS set of libraries, and builds have
consequently started to fail.
This patch passes different sysroots to the linker depending on
whether the target is a iPhoneOS or an iPhoneSimulator.
Bug: 190421934
Test: build succeeded on local machine, awaiting confirmation from maloo@
Change-Id: Ib3d2207d77388c00e8c1e397f6dd13fda1cb4d26

Build changes for XCode 13

---

src/lib/profiles/device-description/DeviceDescription.cpp
src/test-apps/TestDeviceDescriptor.cpp

QR Code parsing is failing when QR code contains leading spaces. 
`Next` function advances the pointer by 1 past `mFieldEnd` to skip the field separator. When empty spaces are present the initial `Next` call advances past the first empty space before performing the empty space check, ending up on the version value instead of the initial key. This change initializes `mFieldEnd` to match `mReadPoint` which is `val` with removed empty spaces.

Fix error in TextDescriptorReader when data contains leading empty spaces
