src/platform/ble/bluez/BluezHelperCode.cpp
src/test-apps/happy/test-templates/WeaveBleCentral.py

The advertisement may not be set iscoverable in some Linu versions. Add
enableAdvertisement to resolve this issue.
Bug: None
Test: Local test

Wobluez Improvement and tests

---

src/lib/profiles/data-management/Current/SubscriptionClient.cpp
src/lib/profiles/data-management/Current/SubscriptionClient.h

Added SubscriptionClient::IsEstablished() and fixed the WDM Update code.

Subscription established means Idle or Confirming

---

src/platform/ble/bluez/BluezBleApplicationDelegate.cpp
src/platform/ble/bluez/BluezHelperCode.cpp

1. Move ble disconnect related logs from WeaveLogProgress to WeaveLogRetain.
2. Correct log description about ble disconnection

Update WoBluez log

---

src/system/SystemTimer.cpp
src/test-apps/TestSystemTimer.cpp

Restructure the RTOS-based timers to handle a bounded number of
expired timers per expiration of the platform timer.  Previously, the
`HandleExpiredTimers` method would continously evaluate the current
list of timers, and keep evaluating the currently expired timers.  If
the timer handler code resulted in posting the timer with an
expiration code in the past (e.g. a timer with expiration time of 0),
the control would not be returned from the timer handling code, and
the as a result, processing of other Weave events would be starved.
The new approach commits to processing all timers expired at the
beginning of the `HandleExpiredTimers` function; any timers created
and expired as a result of the timer handlers will be processed on a
subsequent invocation of the `HandleExpiredTimers`. Added …

Ensure that expired timer processing is bounded

---

.travis.yml
.travis/before_install.sh
.travis/script.sh

travis CI test result link:
https://travis-ci.org/jenniexie/openweave-core/builds/452733670

enable happy test

---

src/device-manager/python/WeaveBluezMgr.py
src/device-manager/python/WeaveCoreBluetoothMgr.py

Adding chromecast setup service uuid to the ble scan filter
Change-Id: Ia4079af9a4df5034b62b76a92236ea7bf988ccfe

Adding chromecast setup service uuid to the ble scan filter

---

.travis.yml
.travis/before_install.sh
.travis/script.sh

Add support for code coverage and basic unit and functional tests against LwIP. Additionally, refactor pre-run dependency installation reduce copy-and-paste code.

Add Support for Code Coverage and Basic Unit and Functional Tests against LwIP

---

src/adaptations/device-layer/ServiceProvisioningServer.cpp
src/adaptations/device-layer/include/Weave/DeviceLayer/internal/ServiceProvisioningServer.h
src/lib/profiles/service-provisioning/ServiceProvisioning.cpp
src/lib/profiles/service-provisioning/ServiceProvisioning.h
src/lib/profiles/service-provisioning/ServiceProvisioningServer.cpp
src/test-apps/MockSPServer.cpp
src/test-apps/MockSPServer.h

Change-Id: I703b90b3ff482390831737144b9e0a89402435e9

Fix conditional compilation issues

---

src/device-manager/WeaveDeviceManager-JNI.cpp
src/device-manager/java/src/nl/Weave/DeviceManager/NetworkInfo.java
src/device-manager/java/src/nl/Weave/DeviceManager/TestMain.java

Improve Weave Device Manager (java) to allow Thread network information objects with explicit Thread PAN identifier and channel values.

Thread improvements to Java device manager.

---

src/device-manager/cocoa/NLNetworkInfo.h
src/device-manager/cocoa/NLNetworkInfo.mm

Improve Weave Device Manager (cocoa) to allow Thread network informationobjects with explicit Thread PAN identifier and channel fields.

Thread improvements to Cocoa device manager.

---

src/test-apps/happy/lib/WeaveNetworkGateway.py
src/test-apps/happy/lib/WeaveNodeConfigure.py
src/test-apps/happy/lib/WeaveState.py
src/test-apps/happy/test-templates/WeaveBDX.py
src/test-apps/happy/test-templates/WeaveBle.py
src/test-apps/happy/test-templates/WeaveDeviceDescription.py
src/test-apps/happy/test-templates/WeaveHeartbeat.py
src/test-apps/happy/test-templates/WeaveKeyExport.py
src/test-apps/happy/test-templates/WeavePairing.py
src/test-apps/happy/test-templates/WeavePing.py
src/test-apps/happy/test-templates/WeaveSWU.py
src/test-apps/happy/test-templates/WeaveSecurityPing.py
src/test-apps/happy/test-templates/WeaveTunnelStart.py
src/test-apps/happy/test-templates/WeaveTunnelStop.py
src/test-apps/happy/test-templates/WeaveWDMv0.py
src/test-apps/happy/test-templates/WeaveWRMP.py
src/test-apps/happy/test-templates/WeaveWdmNext.py

change the way test script call IP.py module util because of below Happy PR:
https://github.com/openweave/happy/pull/10

change IP.py to module util

---

src/test-apps/happy/lib/WeaveNetworkGateway.py

I missed one file related to IP util change by mistake, and fixing it in this PR.
I have double checked again for all functions using IP module util in both openweave-core and Happy repo, that should be the only missing file by mistake.

use isIpAddress from IP util

---

src/test-apps/happy/topologies/standalone/two_nodes_on_tap_wifi.json
src/test-apps/happy/topologies/standalone/two_nodes_on_tap_wifi.sh
src/test-apps/happy/topologies/standalone/two_nodes_on_wifi.json
src/test-apps/happy/topologies/standalone/two_nodes_on_wifi.sh

This adds what will become a new, primary, simple two node "WiFi" topology for testing the Inet layer.

Add New, Simple Two Node "WiFi" Topology That Will Be Used to Test the Inet Layer

---

.travis.yml
.travis/before_install.sh
.travis/build_nrf52840.sh
.travis/prepare_nrf52840.sh
.travis/script.sh
Makefile.am
Makefile.in

-- Added GitHub Travis build automation for nRF52840.

WIP: Device layer port to nRF52840

---

src/platform/ble/bluez/BluezHelperCode.cpp

Unregistering weave advertisement during BluezIOThread closure to stop weave advertisement when WoBluez IO thread is no longer running
Change-Id: Ic0e637f860bbb0247bf46a2002c485ce46889726

[WoBluez] Stopping weave advertisement when BluezIOThread is stopped

---

src/test-apps/happy/bin/weave-register-service.py
src/test-apps/happy/test-templates/ServiceAccountManager.py
src/test-apps/happy/test-templates/WeavePairing.py

Renaming WeaveRegisterService to ServiceAccountManager as first step
This is preparation for another ticket to add unregister service under file ServiceAccountManager

change name to WeaveRegisterService

---

src/device-manager/WeaveDeviceManager.cpp

-- Fixed a logic bug in the WeaveDeviceManager C++ class that resulted in the application’s on-error callback never being called when a connection to a device closed unexpectedly during a connect or rendezvous operation.  In the observed scenario, a spontaneous close of a newly established Weave connection just as a security session was starting would result in the Device Manager ignoring the HandleSessionError() callback from the WeaveSecurityManager, but only in the case where it had received a HandleConnectionClosed() callback prior to the HandleSessionError().
The ordering of the two events depends very much on the behavior of the underlying TCP stack.  Indeed, the situation may only be prevalent on mobile devices, where the network stack immediately invalidates TCP sockets when there …

Fixed hang in Device Manager on unexpected connection close

---

src/test-apps/ToolCommon.cpp

-- Corrected a small logic bug in ToolCommon.cpp, InitNetwork() that resulted in the --node-addr argument being ignored when configuring an LwIP netif.  I also took this opportunity to simplify the code in this area a bit.

Fix for Issue #281: not able to set --node-addr for lwip device

---

src/device-manager/WeaveDeviceManager.cpp
src/lib/profiles/vendor/nestlabs/device-description/NestProductIdentifiers.hpp

Add updated Topaz Product Identifiers to NestProductIdentifiers
Add updated Topaz Product Identifiers to WeaveDeviceManager FilterIdentifyResponse

Add updated Topaz Product Identifiers to NestProductIdentifiers

---

build/esp32/components/openweave/component.mk

-- Fixed a failure when building for the ESP32 on OS X that resulted from not running ranlib on openweave libraries.
-- Fixed a second build failure caused by the use of a GNU-specific install option.
-- Did some minor restructuring of the ESP32 component makefile to make it more like the Nordic makefiles.
This fixes [openweave/openweave-esp32-demo, issue#7](https://github.com/openweave/openweave-esp32-demo/issues/7) and [openweave-core, issues#287](https://github.com/openweave/openweave-core/issues/287)

Fix for ESP32 build failures on OS X 

---

src/test-apps/TestInetEndPoint.cpp

Also fix a handful of typos in printed strings and comments.

Fix two assignments that were meant to be comparisons

---

src/adaptations/device-layer/include/Weave/DeviceLayer/OpenThread/GenericThreadStackManagerImpl_OpenThread.ipp

In order to put OpenThread into a low power mode, one must disable
both the Thread module as well as the Ip6 module in OpenThread.
Modify SetThreadEnable() functions accordingly.  However, the
initialization of the OpenThread stack does not proceed as expected
without enabling Ip6 at initialization; consequently, we enable Ip6 on
init, and disable subsequently on any Thread state change that would
disable the Thread stack.

Fix high power usage in the unprovisioned state

---

src/device-manager/WeaveDeviceManager.cpp
src/device-manager/WeaveDeviceManager.h

Add a new Weave error WEAVE_ERROR_INVALID_DEVICE_DESCRIPTOR.

Add a new function to validate a device identify request.

---

src/test-apps/happy/lib/WeaveNodeConfigure.py
src/test-apps/happy/lib/WeaveState.py
src/test-apps/happy/test-templates/WeavePairing.py

-- pass serial number to mock-device for pairing test

add serial number in pairing test

---

src/test-apps/happy/test-templates/WeaveTunnelStart.py
src/test-apps/happy/tests/standalone/tunnel/test_weave_tunnel_01.py
src/test-apps/happy/topologies/standalone/thread_wifi_on_tap_ap_service.sh

enabling lwip tunnel test: test_weave_tunnel_01.py

enable lwip tunnel test: test_weave_tunnel_01.py

---

src/test-apps/TestWeaveTunnelServer.cpp
src/test-apps/ToolCommon.cpp
src/test-apps/ToolCommonOptions.cpp
src/test-apps/ToolCommonOptions.h

1. added ipv6 command option support in ToolCommon.cpp
2. added ipv6 route for lwip tunnel test

add ipv6 route for lwip tunnel test

---

src/lib/core/WeaveConfig.h
src/lib/core/WeaveMessageLayer.cpp
src/lib/core/WeaveMessageLayer.h
src/lib/profiles/security/WeaveCert.cpp
src/lib/profiles/security/WeaveCert.h
src/lib/support/MathUtils.h
src/lib/support/crypto/EllipticCurve.h
src/test-apps/Makefile.am
src/test-apps/Makefile.in
src/test-apps/TestWeaveCert.cpp
src/test-apps/TestWeaveCertData.cpp
src/test-apps/TestWeaveCertData.h

New helper functions support:
-- Generation of operational Weave device Id.
-- Generation of operational Weave self-signed certificate.
-- Generation of any type of Weave certificate.

Added Helper Functions to Generate Operational Weave Device Credentials.

---

src/tools/simnet/simnet.py

-- Revised the way the user’s shell is invoked when the simnet ‘shell’ command is executed. The new scheme uses sudo to ensure an interactive shell is launched.
-- The above required a change to the scheme used to override the user’s prompt.  In the new
scheme, a temporary override “rc” file is created that sources the user’s main rc files before overriding the shell PS1 variable.
-- Used the --preserve-env=... argument to sudo to ensure that environment variables generated by simnet are passed to the user shell.
-- Corrected name of Weave subnet argument.

More fixes to simnet's shell command [skip ci]

---

src/inet/UDPEndPoint.cpp

-- Fixed a bug where the SOF_REUSEADDR flag was not getting set on a UDP PCB when OpenWeave was compiled with with versions of LwIP later than 1.4.
-- Rewrote UDPEndPoint::GetPCB() in an attempt to simplify the logic and eliminate duplicate code paths.

Fix for issue#383: UDPEndPoint not setting REUSEADDR on later LwIP versions

---

src/test-apps/happy/test-templates/ServiceAccountManager.py

Change is running successfully in internal service tests.

Use updated apigw endpoint w/ secure channel

---

src/adaptations/device-layer/LwIP/WarmSupport.cpp

When the OpenThread interface is disconnected, the Thread stack
removes the addresses on that interface.  By the time WARM has a
chance to deal with the situation, the Weave ULA address is no longer
on the interface, and the LwIP call
`netif_remove_ip6_address_with_route` returns an error code.  In turn,
when WARM observes that the operation to remove the address fails, it
does not update the state accordingly.  When the device rejoins, WARM
(having failed to update the state), does not reassign the Weave ULA
address to the interface.  As a result, all the packets going out to
Weave addresses (and the service address in particular) are sent with
the Thread mesh-local address as the source address and thus fail to
be routed properly.  By squashing the error on remove, we enable the
WARM …

Fix re-joining to the disconnected Thread network

---

src/adaptations/device-layer/nRF5/nRF5Config.cpp

-- Ensure that xSemaphoreGiveFromISR() is called, rather than xSemaphoreGive(), whenever
handling an FDS event from the Nordic SoftDevice.

Fix for issue #419 : nRF52: Crash in FreeRTOS when configASSERT defined

---

src/lib/support/SerializationUtils.cpp

 fix de-serializing for "SerializedFieldTypeInt64"

---

src/include/Makefile.am
src/lib/core/WeaveConfig.h
src/lib/support/crypto/RSA.cpp
src/lib/support/crypto/RSA.h
src/lib/support/gen-oid-table.py

Defined types, objects, and methods for working with RSA
public and private keys and RSA signatures.

Add RSA signature support.

---

BUILDING.md

These packages were added to openweave.io/guides/build, so adding here too to keep in sync.
Also fixed some code-font formatting issues.

Update BUILDING with required Python packages

---

src/lib/support/crypto/HMAC.cpp
src/lib/support/crypto/HMAC.h

Defined types, objects, and methods for working with HMAC signatures.

Add HMAC signature support.

---

src/test-apps/happy/bin/weave-register-service.py
src/test-apps/happy/test-templates/ServiceAccountManager.py

The tool will now support either python 2.7 as before or python 3.

[python3] Extend weave-register-service tool to work on python3

---

src/lib/core/WeaveSecurityMgr.cpp
src/lib/profiles/security/WeaveSecurity.h
src/lib/support/StatusReportStr.cpp
src/test-apps/TestStatusReportStr.cpp

-- kStatusCode_UnathorizedKeyExportRequest --> kStatusCode_UnauthorizedKeyExportRequest
-- kStatusCode_UnathorizedGetCertRequest --> kStatusCode_UnauthorizedGetCertRequest

Fixed Typo in the Status Code.

---

src/lib/core/WeaveDMConfig.h
src/lib/profiles/common/WeaveMessage.cpp
src/lib/profiles/common/WeaveMessage.h
src/lib/profiles/data-management/Current/SubscriptionEngine.cpp
src/lib/profiles/data-management/Current/SubscriptionEngine.h
src/lib/profiles/data-management/Current/TraitData.cpp
src/lib/profiles/data-management/Current/TraitData.h
src/lib/profiles/status-report/StatusReportProfile.cpp
src/lib/profiles/status-report/StatusReportProfile.h
src/test-apps/Makefile.am
src/test-apps/MockSourceTraits.cpp
src/test-apps/MockSourceTraits.h
src/test-apps/MockWdmSubscriptionInitiator.cpp
src/test-apps/MockWdmSubscriptionResponder.cpp
src/test-apps/happy/tests/standalone/wdmNext/test_weave_wdm_next_update_01.py
src/test-apps/happy/tests/standalone/wdmNext/test_weave_wdm_next_update_03.py
src/test-apps/happy/tests/standalone/wdmNext/test_weave_wdm_next_update_04.py
src/test-apps/happy/tests/standalone/wdmNext/test_weave_wdm_next_update_05.py
src/test-apps/mock-device.cpp

-- add wdm update request processing and update response generation
mechanism
-- add TraitUpdatableDataSource

Add wdm update server support

---

src/adaptations/device-layer/GeneralUtils.cpp
src/adaptations/device-layer/include/Weave/DeviceLayer/ConfigurationManager.h
src/adaptations/device-layer/include/Weave/DeviceLayer/PlatformManager.h

Fixes for clang build in Device Layer

---

src/device-manager/java/Makefile.am
src/device-manager/java/WeaveDeviceManager-JNI.cpp
src/device-manager/java/src/nl/Weave/DataManagement/GenericTraitUpdatableDataSink.java
src/device-manager/java/src/nl/Weave/DataManagement/GenericTraitUpdatableDataSinkImpl.java
src/device-manager/java/src/nl/Weave/DataManagement/ResourceIdentifier.java
src/device-manager/java/src/nl/Weave/DataManagement/WdmClient.java
src/device-manager/java/src/nl/Weave/DataManagement/WdmClientFactory.java
src/device-manager/java/src/nl/Weave/DataManagement/WdmClientImpl.java
src/device-manager/java/src/nl/Weave/DeviceManager/TestMain.java
src/device-manager/java/src/nl/Weave/DeviceManager/WeaveDeviceManager.java
src/lib/core/WeaveDMConfig.h

--add JAVA API for dataManagement in client side

Add Java API for DataManagement in client side

---

src/lib/profiles/security/WeaveCertProvisioning.cpp
src/lib/profiles/security/WeaveSecurity.h
src/lib/support/StatusReportStr.cpp
src/test-apps/TestStatusReportStr.cpp

Updated status codes in the Security profile associated with
Certificate Provisioning Protocol.

Updated Security Profiles Status Codes.

---

src/device-manager/WeaveDataManagementClient.cpp
src/lib/profiles/data-management/Current/SubscriptionEngine.cpp

-- Init Uninitialized pointer field in GenericTraitUpdatableDataSink
and WdmClient Constructor
-- Fix Unchecked return value for TLV Next and TLV CopyElement and
MapPathToHandle and Finalize
-- Fix Mixing enum types although kTLVElementType_Null has been casted
to kTLVType_Null

Fix coverity errors/warnings

---

src/device-manager/cocoa/Makefile.am
src/device-manager/cocoa/NLGenericTraitUpdatableDataSink.h
src/device-manager/cocoa/NLGenericTraitUpdatableDataSink.mm
src/device-manager/cocoa/NLGenericTraitUpdatableDataSink_Protected.h
src/device-manager/cocoa/NLResourceIdentifier.h
src/device-manager/cocoa/NLResourceIdentifier.mm
src/device-manager/cocoa/NLResourceIdentifier_Protected.h
src/device-manager/cocoa/NLWdmClient.h
src/device-manager/cocoa/NLWdmClient.mm
src/device-manager/cocoa/NLWdmClient_Protected.h
src/device-manager/cocoa/NLWeaveDeviceManager.h
src/device-manager/cocoa/NLWeaveDeviceManager.mm
src/device-manager/cocoa/NLWeaveLogging.mm
src/device-manager/cocoa/NLWeaveStack.h
src/device-manager/cocoa/NLWeaveStack.mm

-- Add objective-c API for DataManagement in client side

Add objective-c API for DataManagement in client side 

---

src/lib/core/WeaveFabricState.cpp
src/test-apps/weave-ping.cpp

- Ensure that the WeaveSessionKey structure is fully initialized in the case where an existing session with the same key id and peer node id does NOT exist.
- Modified weave-ping tool test exercise the above case.

Fixed bug in WeaveFabricState::RestoreSession()

---

src/lib/profiles/security/WeaveSig.cpp
src/lib/profiles/security/WeaveSig.h

Added function that converts DER encoded signature into Weave signature.

Added Function Converts DER to Weave Signature.

---

src/adaptations/device-layer/NetworkTelemetryManager.cpp

-- Enable the polling timer only when the device is
network provisioined.

Fix a bug in network telemetry manager

---

src/adaptations/device-layer/NetworkTelemetryManager.cpp
src/adaptations/device-layer/include/Weave/DeviceLayer/OpenThread/GenericThreadStackManagerImpl_OpenThread.ipp

-- Remove service provisioning requirement when logging network telemetry data
-- Split long weave log messages in GenericThreadStackManagerImpl_OpenThread

Network telemetry mgr fixes contd

---

src/test-apps/happy/test-templates/ServiceAccountManager.py
src/test-apps/happy/tests/service/pairing/test_weave_pairing_01.py

Needed this update as some test service instances may
require stronger account passwords that also include digits.

Updated Test Account Password Used in Happy Testing.

---

src/lib/profiles/security/WeaveCASE.h
src/lib/profiles/security/WeaveCASEEngine.cpp

Added support for TLV encoded array of intermediate
CA certificates.

Updated EncodeCASECertInfo() Function.

---

src/test-apps/TestWeaveTool.py

MacOS migrated to LibreSSL sometime ago, and the preferred
way to use OpenSSL on MacOS is via `brew`.  This commit alters
the search algorithm for the preferred openssl executable to
first check the directory where brew actually installed the
executable; this addresses dynamic link issues with some partial
openssl installations.

Improve the search for OpenSSL on MacOS

---

src/lib/profiles/data-management/Current/SubscriptionClient.cpp

Change-Id: I67687e24842cd0ee724fedccb7c11540958f4b74

Removed unused local variables that skipped by in the review process

---

src/lib/core/WeaveConnection.cpp

Modified WeaveConnection::HandleDataReceived() to properly handle the case where an incoming Weave message arrives in multiple TCP segments and the underlying network driver places the first such segment into a packet buffer that is too small to hold the entire message.
Since the message decoding logic in Weave requires message data to be in a contiguous region of memory, code in HandleDataReceived() automatically copies message data received after the initial segment into the initial packet buffer, expecting that buffer to always be big enough to hold the entire message.  However if the underlying network driver places incoming packets into buffers sized only big enough to fit the packet data, reception of large Weave messages fails with WEAVE_ERROR_MESSAGE_TOO_LONG.
The fix is to detect …

Fix for Message Too Long error

---

src/lib/core/WeaveCircularTLVBuffer.h
src/lib/core/WeaveTLV.h
src/lib/core/WeaveTLVWriter.cpp
src/lib/profiles/data-management/Current/EventLoggingTags.h
src/lib/profiles/data-management/Current/LoggingManagement.cpp
src/lib/profiles/data-management/Current/LoggingManagement.h
src/lib/support/PersistedCounter.cpp
src/lib/support/PersistedCounter.h

-Serializes and persit events stored in WeaveCircularTLVBuffer and associated states
-Use ShutdownInProgress flag to suspend logging manager during shutdown process

Persist Event

---

src/lib/profiles/data-management/Current/TraitData.h

Calculate hash of serialized trait and compare it to persisted value. If consistent, load trait version from persisted storage.

Load trait version from persisted storage

---

.travis/before_install.sh
src/test-apps/happy/lib/WeaveDeviceManager.py

-- Previous happy python3 change miss
testWdmClientDataSinkSetFlushInvalidInstanceId test in previous PR, we
fix the python3 syntax error.
-- Previous travis ci point to particular happy python3 branch, now
switch to master branch.

Fix weaave happy py3 bug

---

src/lib/profiles/data-management/Current/LoggingManagement.cpp
src/lib/profiles/data-management/Current/NotificationEngine.cpp

This PR also changes dropping event log to debug level

Fix importance level in the log

---

src/device-manager/cocoa/NLWeaveStack.mm
src/device-manager/java/WeaveDeviceManager-JNI.cpp
src/device-manager/python/WeaveDeviceManager-ScriptBinding.cpp
src/examples/weave-app-common.cpp
src/inet/InetLayer.cpp
src/inet/InetLayer.h
src/inet/InetLayerBasis.cpp
src/inet/InetLayerBasis.h
src/inet/RawEndPoint.cpp
src/inet/TCPEndPoint.cpp
src/inet/UDPEndPoint.cpp
src/lib/core/WeaveConfig.h
src/system/SystemLayer.cpp
src/system/SystemLayer.h
src/test-apps/AndroidTest.cpp
src/test-apps/TestSystemTimer.cpp
src/test-apps/ToolCommon.cpp

There is a limitation of `select` that it is unable to poll fd larger than 1023.

Use poll instead of select

---

src/device-manager/cocoa/NLWeaveStack.mm

`pollFDs` needs to be writable in the block, change it into a `__block` variable. And C array can not be passed into a block, use `std::array` instead.

Fix Darwin build

---

src/inet/InetLayerBasis.h
src/system/SystemLayer.h

Change-Id: I7ebf34d7ec2991cb5fc2222c1a7a933529c53a23

Remove unused header include
